/* Autogenerated file. Do not edit manually. */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { Collateral, CollateralInterface } from "../Collateral";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
    ],
    name: "AlreadyResigned",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
    ],
    name: "NotResigned",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
    ],
    name: "NothingToWithdraw",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "resignationBlockNum",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "resignDelayInBlocks",
        type: "uint256",
      },
    ],
    name: "ResignationDelayNotMet",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "WithdrawalFailed",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "addr",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "PegInCollateralAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "addr",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "PegOutCollateralAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "liquidityProvider",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "punisher",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "quoteHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "enum Flyover.ProviderType",
        name: "collateralType",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "penalty",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "reward",
        type: "uint256",
      },
    ],
    name: "Penalized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "addr",
        type: "address",
      },
    ],
    name: "Resigned",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "addr",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "RewardsWithdrawn",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "addr",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "WithdrawCollateral",
    type: "event",
  },
  {
    inputs: [],
    name: "addPegInCollateral",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "addr",
        type: "address",
      },
    ],
    name: "addPegInCollateralTo",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "addPegOutCollateral",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "addr",
        type: "address",
      },
    ],
    name: "addPegOutCollateralTo",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "getMinCollateral",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "addr",
        type: "address",
      },
    ],
    name: "getPegInCollateral",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "addr",
        type: "address",
      },
    ],
    name: "getPegOutCollateral",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getPenalties",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getResignDelayInBlocks",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "addr",
        type: "address",
      },
    ],
    name: "getResignationBlock",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getRewardPercentage",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "addr",
        type: "address",
      },
    ],
    name: "getRewards",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "enum Flyover.ProviderType",
        name: "providerType",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "addr",
        type: "address",
      },
    ],
    name: "isCollateralSufficient",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "enum Flyover.ProviderType",
        name: "providerType",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "addr",
        type: "address",
      },
    ],
    name: "isRegistered",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "resign",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "punisher",
        type: "address",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "callFee",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "penaltyFee",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "value",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "productFeeAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "gasFee",
            type: "uint256",
          },
          {
            internalType: "bytes20",
            name: "fedBtcAddress",
            type: "bytes20",
          },
          {
            internalType: "address",
            name: "lbcAddress",
            type: "address",
          },
          {
            internalType: "address",
            name: "liquidityProviderRskAddress",
            type: "address",
          },
          {
            internalType: "address",
            name: "contractAddress",
            type: "address",
          },
          {
            internalType: "address payable",
            name: "rskRefundAddress",
            type: "address",
          },
          {
            internalType: "int64",
            name: "nonce",
            type: "int64",
          },
          {
            internalType: "uint32",
            name: "gasLimit",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "agreementTimestamp",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "timeForDeposit",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "callTime",
            type: "uint32",
          },
          {
            internalType: "uint16",
            name: "depositConfirmations",
            type: "uint16",
          },
          {
            internalType: "bool",
            name: "callOnRegister",
            type: "bool",
          },
          {
            internalType: "bytes",
            name: "btcRefundAddress",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "liquidityProviderBtcAddress",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "data",
            type: "bytes",
          },
        ],
        internalType: "struct Quotes.PegInQuote",
        name: "quote",
        type: "tuple",
      },
      {
        internalType: "bytes32",
        name: "quoteHash",
        type: "bytes32",
      },
    ],
    name: "slashPegInCollateral",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "punisher",
        type: "address",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "callFee",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "penaltyFee",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "value",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "productFeeAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "gasFee",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "lbcAddress",
            type: "address",
          },
          {
            internalType: "address",
            name: "lpRskAddress",
            type: "address",
          },
          {
            internalType: "address",
            name: "rskRefundAddress",
            type: "address",
          },
          {
            internalType: "int64",
            name: "nonce",
            type: "int64",
          },
          {
            internalType: "uint32",
            name: "agreementTimestamp",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "depositDateLimit",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "transferTime",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "expireDate",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "expireBlock",
            type: "uint32",
          },
          {
            internalType: "uint16",
            name: "depositConfirmations",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "transferConfirmations",
            type: "uint16",
          },
          {
            internalType: "bytes",
            name: "depositAddress",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "btcRefundAddress",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "lpBtcAddress",
            type: "bytes",
          },
        ],
        internalType: "struct Quotes.PegOutQuote",
        name: "quote",
        type: "tuple",
      },
      {
        internalType: "bytes32",
        name: "quoteHash",
        type: "bytes32",
      },
    ],
    name: "slashPegOutCollateral",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "withdrawCollateral",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "withdrawRewards",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class Collateral__factory {
  static readonly abi = _abi;
  static createInterface(): CollateralInterface {
    return new utils.Interface(_abi) as CollateralInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Collateral {
    return new Contract(address, _abi, signerOrProvider) as Collateral;
  }
}
