/* Autogenerated file. Do not edit manually. */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { Pegout, PegoutInterface } from "../Pegout";

const _abi = [
  {
    type: "function",
    name: "depositPegOut",
    inputs: [
      {
        name: "quote",
        type: "tuple",
        internalType: "struct Quotes.PegOutQuote",
        components: [
          {
            name: "callFee",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "penaltyFee",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "value",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "gasFee",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "lbcAddress",
            type: "address",
            internalType: "address",
          },
          {
            name: "lpRskAddress",
            type: "address",
            internalType: "address",
          },
          {
            name: "rskRefundAddress",
            type: "address",
            internalType: "address",
          },
          {
            name: "nonce",
            type: "int64",
            internalType: "int64",
          },
          {
            name: "agreementTimestamp",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "depositDateLimit",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "transferTime",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "expireDate",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "expireBlock",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "depositConfirmations",
            type: "uint16",
            internalType: "uint16",
          },
          {
            name: "transferConfirmations",
            type: "uint16",
            internalType: "uint16",
          },
          {
            name: "depositAddress",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "btcRefundAddress",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "lpBtcAddress",
            type: "bytes",
            internalType: "bytes",
          },
        ],
      },
      {
        name: "signature",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "hashPegOutQuote",
    inputs: [
      {
        name: "quote",
        type: "tuple",
        internalType: "struct Quotes.PegOutQuote",
        components: [
          {
            name: "callFee",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "penaltyFee",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "value",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "gasFee",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "lbcAddress",
            type: "address",
            internalType: "address",
          },
          {
            name: "lpRskAddress",
            type: "address",
            internalType: "address",
          },
          {
            name: "rskRefundAddress",
            type: "address",
            internalType: "address",
          },
          {
            name: "nonce",
            type: "int64",
            internalType: "int64",
          },
          {
            name: "agreementTimestamp",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "depositDateLimit",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "transferTime",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "expireDate",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "expireBlock",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "depositConfirmations",
            type: "uint16",
            internalType: "uint16",
          },
          {
            name: "transferConfirmations",
            type: "uint16",
            internalType: "uint16",
          },
          {
            name: "depositAddress",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "btcRefundAddress",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "lpBtcAddress",
            type: "bytes",
            internalType: "bytes",
          },
        ],
      },
    ],
    outputs: [
      {
        name: "",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isQuoteCompleted",
    inputs: [
      {
        name: "quoteHash",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pause",
    inputs: [
      {
        name: "reason",
        type: "string",
        internalType: "string",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "pauseStatus",
    inputs: [],
    outputs: [
      {
        name: "isPaused",
        type: "bool",
        internalType: "bool",
      },
      {
        name: "reason",
        type: "string",
        internalType: "string",
      },
      {
        name: "since",
        type: "uint64",
        internalType: "uint64",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "refundPegOut",
    inputs: [
      {
        name: "quoteHash",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "btcTx",
        type: "bytes",
        internalType: "bytes",
      },
      {
        name: "btcBlockHeaderHash",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "merkleBranchPath",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "merkleBranchHashes",
        type: "bytes32[]",
        internalType: "bytes32[]",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "refundUserPegOut",
    inputs: [
      {
        name: "quoteHash",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "unpause",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "validatePegout",
    inputs: [
      {
        name: "quoteHash",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "btcTx",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [
      {
        name: "quote",
        type: "tuple",
        internalType: "struct Quotes.PegOutQuote",
        components: [
          {
            name: "callFee",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "penaltyFee",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "value",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "gasFee",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "lbcAddress",
            type: "address",
            internalType: "address",
          },
          {
            name: "lpRskAddress",
            type: "address",
            internalType: "address",
          },
          {
            name: "rskRefundAddress",
            type: "address",
            internalType: "address",
          },
          {
            name: "nonce",
            type: "int64",
            internalType: "int64",
          },
          {
            name: "agreementTimestamp",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "depositDateLimit",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "transferTime",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "expireDate",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "expireBlock",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "depositConfirmations",
            type: "uint16",
            internalType: "uint16",
          },
          {
            name: "transferConfirmations",
            type: "uint16",
            internalType: "uint16",
          },
          {
            name: "depositAddress",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "btcRefundAddress",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "lpBtcAddress",
            type: "bytes",
            internalType: "bytes",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "PegOutChangePaid",
    inputs: [
      {
        name: "quoteHash",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "userAddress",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "change",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PegOutDeposit",
    inputs: [
      {
        name: "quoteHash",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "sender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "timestamp",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PegOutRefunded",
    inputs: [
      {
        name: "quoteHash",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PegOutUserRefunded",
    inputs: [
      {
        name: "quoteHash",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "userAddress",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "value",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "InvalidDestination",
    inputs: [
      {
        name: "expected",
        type: "bytes",
        internalType: "bytes",
      },
      {
        name: "actual",
        type: "bytes",
        internalType: "bytes",
      },
    ],
  },
  {
    type: "error",
    name: "InvalidQuoteHash",
    inputs: [
      {
        name: "expected",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "actual",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "MalformedTransaction",
    inputs: [
      {
        name: "outputScript",
        type: "bytes",
        internalType: "bytes",
      },
    ],
  },
  {
    type: "error",
    name: "NotEnoughConfirmations",
    inputs: [
      {
        name: "required",
        type: "int256",
        internalType: "int256",
      },
      {
        name: "current",
        type: "int256",
        internalType: "int256",
      },
    ],
  },
  {
    type: "error",
    name: "QuoteAlreadyCompleted",
    inputs: [
      {
        name: "quoteHash",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "QuoteAlreadyRegistered",
    inputs: [
      {
        name: "quoteHash",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "QuoteExpiredByBlocks",
    inputs: [
      {
        name: "expireBlock",
        type: "uint32",
        internalType: "uint32",
      },
    ],
  },
  {
    type: "error",
    name: "QuoteExpiredByTime",
    inputs: [
      {
        name: "depositDateLimit",
        type: "uint32",
        internalType: "uint32",
      },
      {
        name: "expireDate",
        type: "uint32",
        internalType: "uint32",
      },
    ],
  },
  {
    type: "error",
    name: "QuoteNotExpired",
    inputs: [
      {
        name: "quoteHash",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "UnableToGetConfirmations",
    inputs: [
      {
        name: "errorCode",
        type: "int256",
        internalType: "int256",
      },
    ],
  },
] as const;

export class Pegout__factory {
  static readonly abi = _abi;
  static createInterface(): PegoutInterface {
    return new utils.Interface(_abi) as PegoutInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Pegout {
    return new Contract(address, _abi, signerOrProvider) as Pegout;
  }
}
