/* Autogenerated file. Do not edit manually. */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export declare namespace Quotes {
  export type PegInQuoteStruct = {
    callFee: BigNumberish;
    penaltyFee: BigNumberish;
    value: BigNumberish;
    productFeeAmount: BigNumberish;
    gasFee: BigNumberish;
    fedBtcAddress: BytesLike;
    lbcAddress: string;
    liquidityProviderRskAddress: string;
    contractAddress: string;
    rskRefundAddress: string;
    nonce: BigNumberish;
    gasLimit: BigNumberish;
    agreementTimestamp: BigNumberish;
    timeForDeposit: BigNumberish;
    callTime: BigNumberish;
    depositConfirmations: BigNumberish;
    callOnRegister: boolean;
    btcRefundAddress: BytesLike;
    liquidityProviderBtcAddress: BytesLike;
    data: BytesLike;
  };

  export type PegInQuoteStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    string,
    string,
    string,
    string,
    BigNumber,
    number,
    number,
    number,
    number,
    number,
    boolean,
    string,
    string,
    string
  ] & {
    callFee: BigNumber;
    penaltyFee: BigNumber;
    value: BigNumber;
    productFeeAmount: BigNumber;
    gasFee: BigNumber;
    fedBtcAddress: string;
    lbcAddress: string;
    liquidityProviderRskAddress: string;
    contractAddress: string;
    rskRefundAddress: string;
    nonce: BigNumber;
    gasLimit: number;
    agreementTimestamp: number;
    timeForDeposit: number;
    callTime: number;
    depositConfirmations: number;
    callOnRegister: boolean;
    btcRefundAddress: string;
    liquidityProviderBtcAddress: string;
    data: string;
  };

  export type PegOutQuoteStruct = {
    callFee: BigNumberish;
    penaltyFee: BigNumberish;
    value: BigNumberish;
    productFeeAmount: BigNumberish;
    gasFee: BigNumberish;
    lbcAddress: string;
    lpRskAddress: string;
    rskRefundAddress: string;
    nonce: BigNumberish;
    agreementTimestamp: BigNumberish;
    depositDateLimit: BigNumberish;
    transferTime: BigNumberish;
    expireDate: BigNumberish;
    expireBlock: BigNumberish;
    depositConfirmations: BigNumberish;
    transferConfirmations: BigNumberish;
    depositAddress: BytesLike;
    btcRefundAddress: BytesLike;
    lpBtcAddress: BytesLike;
  };

  export type PegOutQuoteStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    string,
    string,
    BigNumber,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    string,
    string,
    string
  ] & {
    callFee: BigNumber;
    penaltyFee: BigNumber;
    value: BigNumber;
    productFeeAmount: BigNumber;
    gasFee: BigNumber;
    lbcAddress: string;
    lpRskAddress: string;
    rskRefundAddress: string;
    nonce: BigNumber;
    agreementTimestamp: number;
    depositDateLimit: number;
    transferTime: number;
    expireDate: number;
    expireBlock: number;
    depositConfirmations: number;
    transferConfirmations: number;
    depositAddress: string;
    btcRefundAddress: string;
    lpBtcAddress: string;
  };
}

export interface CollateralInterface extends utils.Interface {
  functions: {
    "addPegInCollateral()": FunctionFragment;
    "addPegInCollateralTo(address)": FunctionFragment;
    "addPegOutCollateral()": FunctionFragment;
    "addPegOutCollateralTo(address)": FunctionFragment;
    "getMinCollateral()": FunctionFragment;
    "getPegInCollateral(address)": FunctionFragment;
    "getPegOutCollateral(address)": FunctionFragment;
    "getPenalties()": FunctionFragment;
    "getResignDelayInBlocks()": FunctionFragment;
    "getResignationBlock(address)": FunctionFragment;
    "getRewardPercentage()": FunctionFragment;
    "getRewards(address)": FunctionFragment;
    "isCollateralSufficient(uint8,address)": FunctionFragment;
    "isRegistered(uint8,address)": FunctionFragment;
    "resign()": FunctionFragment;
    "slashPegInCollateral(address,(uint256,uint256,uint256,uint256,uint256,bytes20,address,address,address,address,int64,uint32,uint32,uint32,uint32,uint16,bool,bytes,bytes,bytes),bytes32)": FunctionFragment;
    "slashPegOutCollateral(address,(uint256,uint256,uint256,uint256,uint256,address,address,address,int64,uint32,uint32,uint32,uint32,uint32,uint16,uint16,bytes,bytes,bytes),bytes32)": FunctionFragment;
    "withdrawCollateral()": FunctionFragment;
    "withdrawRewards()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addPegInCollateral"
      | "addPegInCollateralTo"
      | "addPegOutCollateral"
      | "addPegOutCollateralTo"
      | "getMinCollateral"
      | "getPegInCollateral"
      | "getPegOutCollateral"
      | "getPenalties"
      | "getResignDelayInBlocks"
      | "getResignationBlock"
      | "getRewardPercentage"
      | "getRewards"
      | "isCollateralSufficient"
      | "isRegistered"
      | "resign"
      | "slashPegInCollateral"
      | "slashPegOutCollateral"
      | "withdrawCollateral"
      | "withdrawRewards"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addPegInCollateral",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addPegInCollateralTo",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "addPegOutCollateral",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addPegOutCollateralTo",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getMinCollateral",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPegInCollateral",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPegOutCollateral",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPenalties",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getResignDelayInBlocks",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getResignationBlock",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRewardPercentage",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getRewards", values: [string]): string;
  encodeFunctionData(
    functionFragment: "isCollateralSufficient",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "resign", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "slashPegInCollateral",
    values: [string, Quotes.PegInQuoteStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "slashPegOutCollateral",
    values: [string, Quotes.PegOutQuoteStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawCollateral",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawRewards",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "addPegInCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addPegInCollateralTo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addPegOutCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addPegOutCollateralTo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMinCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPegInCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPegOutCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPenalties",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getResignDelayInBlocks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getResignationBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRewardPercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRewards", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isCollateralSufficient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resign", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "slashPegInCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "slashPegOutCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawRewards",
    data: BytesLike
  ): Result;

  events: {
    "PegInCollateralAdded(address,uint256)": EventFragment;
    "PegOutCollateralAdded(address,uint256)": EventFragment;
    "Penalized(address,address,bytes32,uint8,uint256,uint256)": EventFragment;
    "Resigned(address)": EventFragment;
    "RewardsWithdrawn(address,uint256)": EventFragment;
    "WithdrawCollateral(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "PegInCollateralAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PegOutCollateralAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Penalized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Resigned"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RewardsWithdrawn"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WithdrawCollateral"): EventFragment;
}

export interface PegInCollateralAddedEventObject {
  addr: string;
  amount: BigNumber;
}
export type PegInCollateralAddedEvent = TypedEvent<
  [string, BigNumber],
  PegInCollateralAddedEventObject
>;

export type PegInCollateralAddedEventFilter =
  TypedEventFilter<PegInCollateralAddedEvent>;

export interface PegOutCollateralAddedEventObject {
  addr: string;
  amount: BigNumber;
}
export type PegOutCollateralAddedEvent = TypedEvent<
  [string, BigNumber],
  PegOutCollateralAddedEventObject
>;

export type PegOutCollateralAddedEventFilter =
  TypedEventFilter<PegOutCollateralAddedEvent>;

export interface PenalizedEventObject {
  liquidityProvider: string;
  punisher: string;
  quoteHash: string;
  collateralType: number;
  penalty: BigNumber;
  reward: BigNumber;
}
export type PenalizedEvent = TypedEvent<
  [string, string, string, number, BigNumber, BigNumber],
  PenalizedEventObject
>;

export type PenalizedEventFilter = TypedEventFilter<PenalizedEvent>;

export interface ResignedEventObject {
  addr: string;
}
export type ResignedEvent = TypedEvent<[string], ResignedEventObject>;

export type ResignedEventFilter = TypedEventFilter<ResignedEvent>;

export interface RewardsWithdrawnEventObject {
  addr: string;
  amount: BigNumber;
}
export type RewardsWithdrawnEvent = TypedEvent<
  [string, BigNumber],
  RewardsWithdrawnEventObject
>;

export type RewardsWithdrawnEventFilter =
  TypedEventFilter<RewardsWithdrawnEvent>;

export interface WithdrawCollateralEventObject {
  addr: string;
  amount: BigNumber;
}
export type WithdrawCollateralEvent = TypedEvent<
  [string, BigNumber],
  WithdrawCollateralEventObject
>;

export type WithdrawCollateralEventFilter =
  TypedEventFilter<WithdrawCollateralEvent>;

export interface Collateral extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CollateralInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addPegInCollateral(
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    addPegInCollateralTo(
      addr: string,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    addPegOutCollateral(
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    addPegOutCollateralTo(
      addr: string,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    getMinCollateral(overrides?: CallOverrides): Promise<[BigNumber]>;

    getPegInCollateral(
      addr: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getPegOutCollateral(
      addr: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getPenalties(overrides?: CallOverrides): Promise<[BigNumber]>;

    getResignDelayInBlocks(overrides?: CallOverrides): Promise<[BigNumber]>;

    getResignationBlock(
      addr: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getRewardPercentage(overrides?: CallOverrides): Promise<[BigNumber]>;

    getRewards(addr: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    isCollateralSufficient(
      providerType: BigNumberish,
      addr: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isRegistered(
      providerType: BigNumberish,
      addr: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    resign(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    slashPegInCollateral(
      punisher: string,
      quote: Quotes.PegInQuoteStruct,
      quoteHash: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    slashPegOutCollateral(
      punisher: string,
      quote: Quotes.PegOutQuoteStruct,
      quoteHash: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    withdrawCollateral(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    withdrawRewards(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  addPegInCollateral(
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  addPegInCollateralTo(
    addr: string,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  addPegOutCollateral(
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  addPegOutCollateralTo(
    addr: string,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  getMinCollateral(overrides?: CallOverrides): Promise<BigNumber>;

  getPegInCollateral(
    addr: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPegOutCollateral(
    addr: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPenalties(overrides?: CallOverrides): Promise<BigNumber>;

  getResignDelayInBlocks(overrides?: CallOverrides): Promise<BigNumber>;

  getResignationBlock(
    addr: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getRewardPercentage(overrides?: CallOverrides): Promise<BigNumber>;

  getRewards(addr: string, overrides?: CallOverrides): Promise<BigNumber>;

  isCollateralSufficient(
    providerType: BigNumberish,
    addr: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isRegistered(
    providerType: BigNumberish,
    addr: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  resign(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  slashPegInCollateral(
    punisher: string,
    quote: Quotes.PegInQuoteStruct,
    quoteHash: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  slashPegOutCollateral(
    punisher: string,
    quote: Quotes.PegOutQuoteStruct,
    quoteHash: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  withdrawCollateral(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  withdrawRewards(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    addPegInCollateral(overrides?: CallOverrides): Promise<void>;

    addPegInCollateralTo(
      addr: string,
      overrides?: CallOverrides
    ): Promise<void>;

    addPegOutCollateral(overrides?: CallOverrides): Promise<void>;

    addPegOutCollateralTo(
      addr: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getMinCollateral(overrides?: CallOverrides): Promise<BigNumber>;

    getPegInCollateral(
      addr: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPegOutCollateral(
      addr: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPenalties(overrides?: CallOverrides): Promise<BigNumber>;

    getResignDelayInBlocks(overrides?: CallOverrides): Promise<BigNumber>;

    getResignationBlock(
      addr: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRewardPercentage(overrides?: CallOverrides): Promise<BigNumber>;

    getRewards(addr: string, overrides?: CallOverrides): Promise<BigNumber>;

    isCollateralSufficient(
      providerType: BigNumberish,
      addr: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isRegistered(
      providerType: BigNumberish,
      addr: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    resign(overrides?: CallOverrides): Promise<void>;

    slashPegInCollateral(
      punisher: string,
      quote: Quotes.PegInQuoteStruct,
      quoteHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    slashPegOutCollateral(
      punisher: string,
      quote: Quotes.PegOutQuoteStruct,
      quoteHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawCollateral(overrides?: CallOverrides): Promise<void>;

    withdrawRewards(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "PegInCollateralAdded(address,uint256)"(
      addr?: string | null,
      amount?: BigNumberish | null
    ): PegInCollateralAddedEventFilter;
    PegInCollateralAdded(
      addr?: string | null,
      amount?: BigNumberish | null
    ): PegInCollateralAddedEventFilter;

    "PegOutCollateralAdded(address,uint256)"(
      addr?: string | null,
      amount?: BigNumberish | null
    ): PegOutCollateralAddedEventFilter;
    PegOutCollateralAdded(
      addr?: string | null,
      amount?: BigNumberish | null
    ): PegOutCollateralAddedEventFilter;

    "Penalized(address,address,bytes32,uint8,uint256,uint256)"(
      liquidityProvider?: string | null,
      punisher?: string | null,
      quoteHash?: BytesLike | null,
      collateralType?: null,
      penalty?: null,
      reward?: null
    ): PenalizedEventFilter;
    Penalized(
      liquidityProvider?: string | null,
      punisher?: string | null,
      quoteHash?: BytesLike | null,
      collateralType?: null,
      penalty?: null,
      reward?: null
    ): PenalizedEventFilter;

    "Resigned(address)"(addr?: string | null): ResignedEventFilter;
    Resigned(addr?: string | null): ResignedEventFilter;

    "RewardsWithdrawn(address,uint256)"(
      addr?: string | null,
      amount?: BigNumberish | null
    ): RewardsWithdrawnEventFilter;
    RewardsWithdrawn(
      addr?: string | null,
      amount?: BigNumberish | null
    ): RewardsWithdrawnEventFilter;

    "WithdrawCollateral(address,uint256)"(
      addr?: string | null,
      amount?: BigNumberish | null
    ): WithdrawCollateralEventFilter;
    WithdrawCollateral(
      addr?: string | null,
      amount?: BigNumberish | null
    ): WithdrawCollateralEventFilter;
  };

  estimateGas: {
    addPegInCollateral(
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    addPegInCollateralTo(
      addr: string,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    addPegOutCollateral(
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    addPegOutCollateralTo(
      addr: string,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    getMinCollateral(overrides?: CallOverrides): Promise<BigNumber>;

    getPegInCollateral(
      addr: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPegOutCollateral(
      addr: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPenalties(overrides?: CallOverrides): Promise<BigNumber>;

    getResignDelayInBlocks(overrides?: CallOverrides): Promise<BigNumber>;

    getResignationBlock(
      addr: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRewardPercentage(overrides?: CallOverrides): Promise<BigNumber>;

    getRewards(addr: string, overrides?: CallOverrides): Promise<BigNumber>;

    isCollateralSufficient(
      providerType: BigNumberish,
      addr: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isRegistered(
      providerType: BigNumberish,
      addr: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    resign(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    slashPegInCollateral(
      punisher: string,
      quote: Quotes.PegInQuoteStruct,
      quoteHash: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    slashPegOutCollateral(
      punisher: string,
      quote: Quotes.PegOutQuoteStruct,
      quoteHash: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    withdrawCollateral(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    withdrawRewards(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addPegInCollateral(
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    addPegInCollateralTo(
      addr: string,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    addPegOutCollateral(
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    addPegOutCollateralTo(
      addr: string,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getMinCollateral(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getPegInCollateral(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPegOutCollateral(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPenalties(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getResignDelayInBlocks(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getResignationBlock(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRewardPercentage(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRewards(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isCollateralSufficient(
      providerType: BigNumberish,
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isRegistered(
      providerType: BigNumberish,
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    resign(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    slashPegInCollateral(
      punisher: string,
      quote: Quotes.PegInQuoteStruct,
      quoteHash: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    slashPegOutCollateral(
      punisher: string,
      quote: Quotes.PegOutQuoteStruct,
      quoteHash: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    withdrawCollateral(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    withdrawRewards(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
