/* Autogenerated file. Do not edit manually. */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export declare namespace Flyover {
  export type LiquidityProviderStruct = {
    id: BigNumberish;
    providerAddress: string;
    status: boolean;
    providerType: BigNumberish;
    name: string;
    apiBaseUrl: string;
  };

  export type LiquidityProviderStructOutput = [
    BigNumber,
    string,
    boolean,
    number,
    string,
    string
  ] & {
    id: BigNumber;
    providerAddress: string;
    status: boolean;
    providerType: number;
    name: string;
    apiBaseUrl: string;
  };
}

export interface DiscoveryInterface extends utils.Interface {
  functions: {
    "getProvider(address)": FunctionFragment;
    "getProviders()": FunctionFragment;
    "getProvidersId()": FunctionFragment;
    "isOperational(uint8,address)": FunctionFragment;
    "pause(string)": FunctionFragment;
    "pauseStatus()": FunctionFragment;
    "register(string,string,bool,uint8)": FunctionFragment;
    "setProviderStatus(uint256,bool)": FunctionFragment;
    "unpause()": FunctionFragment;
    "updateProvider(string,string)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getProvider"
      | "getProviders"
      | "getProvidersId"
      | "isOperational"
      | "pause"
      | "pauseStatus"
      | "register"
      | "setProviderStatus"
      | "unpause"
      | "updateProvider"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "getProvider", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getProviders",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProvidersId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isOperational",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "pause", values: [string]): string;
  encodeFunctionData(
    functionFragment: "pauseStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [string, string, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setProviderStatus",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateProvider",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProviders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProvidersId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isOperational",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pauseStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setProviderStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateProvider",
    data: BytesLike
  ): Result;

  events: {
    "ProviderStatusSet(uint256,bool)": EventFragment;
    "ProviderUpdate(address,string,string)": EventFragment;
    "Register(uint256,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ProviderStatusSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProviderUpdate"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Register"): EventFragment;
}

export interface ProviderStatusSetEventObject {
  id: BigNumber;
  status: boolean;
}
export type ProviderStatusSetEvent = TypedEvent<
  [BigNumber, boolean],
  ProviderStatusSetEventObject
>;

export type ProviderStatusSetEventFilter =
  TypedEventFilter<ProviderStatusSetEvent>;

export interface ProviderUpdateEventObject {
  from: string;
  name: string;
  apiBaseUrl: string;
}
export type ProviderUpdateEvent = TypedEvent<
  [string, string, string],
  ProviderUpdateEventObject
>;

export type ProviderUpdateEventFilter = TypedEventFilter<ProviderUpdateEvent>;

export interface RegisterEventObject {
  id: BigNumber;
  from: string;
  amount: BigNumber;
}
export type RegisterEvent = TypedEvent<
  [BigNumber, string, BigNumber],
  RegisterEventObject
>;

export type RegisterEventFilter = TypedEventFilter<RegisterEvent>;

export interface Discovery extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DiscoveryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getProvider(
      providerAddress: string,
      overrides?: CallOverrides
    ): Promise<[Flyover.LiquidityProviderStructOutput]>;

    getProviders(
      overrides?: CallOverrides
    ): Promise<[Flyover.LiquidityProviderStructOutput[]]>;

    getProvidersId(overrides?: CallOverrides): Promise<[BigNumber]>;

    isOperational(
      providerType: BigNumberish,
      addr: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    pause(
      reason: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    pauseStatus(
      overrides?: CallOverrides
    ): Promise<
      [boolean, string, BigNumber] & {
        isPaused: boolean;
        reason: string;
        since: BigNumber;
      }
    >;

    register(
      name: string,
      apiBaseUrl: string,
      status: boolean,
      providerType: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    setProviderStatus(
      providerId: BigNumberish,
      status: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    unpause(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    updateProvider(
      name: string,
      apiBaseUrl: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  getProvider(
    providerAddress: string,
    overrides?: CallOverrides
  ): Promise<Flyover.LiquidityProviderStructOutput>;

  getProviders(
    overrides?: CallOverrides
  ): Promise<Flyover.LiquidityProviderStructOutput[]>;

  getProvidersId(overrides?: CallOverrides): Promise<BigNumber>;

  isOperational(
    providerType: BigNumberish,
    addr: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  pause(
    reason: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  pauseStatus(
    overrides?: CallOverrides
  ): Promise<
    [boolean, string, BigNumber] & {
      isPaused: boolean;
      reason: string;
      since: BigNumber;
    }
  >;

  register(
    name: string,
    apiBaseUrl: string,
    status: boolean,
    providerType: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  setProviderStatus(
    providerId: BigNumberish,
    status: boolean,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  unpause(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  updateProvider(
    name: string,
    apiBaseUrl: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    getProvider(
      providerAddress: string,
      overrides?: CallOverrides
    ): Promise<Flyover.LiquidityProviderStructOutput>;

    getProviders(
      overrides?: CallOverrides
    ): Promise<Flyover.LiquidityProviderStructOutput[]>;

    getProvidersId(overrides?: CallOverrides): Promise<BigNumber>;

    isOperational(
      providerType: BigNumberish,
      addr: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    pause(reason: string, overrides?: CallOverrides): Promise<void>;

    pauseStatus(
      overrides?: CallOverrides
    ): Promise<
      [boolean, string, BigNumber] & {
        isPaused: boolean;
        reason: string;
        since: BigNumber;
      }
    >;

    register(
      name: string,
      apiBaseUrl: string,
      status: boolean,
      providerType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setProviderStatus(
      providerId: BigNumberish,
      status: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    unpause(overrides?: CallOverrides): Promise<void>;

    updateProvider(
      name: string,
      apiBaseUrl: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "ProviderStatusSet(uint256,bool)"(
      id?: BigNumberish | null,
      status?: boolean | null
    ): ProviderStatusSetEventFilter;
    ProviderStatusSet(
      id?: BigNumberish | null,
      status?: boolean | null
    ): ProviderStatusSetEventFilter;

    "ProviderUpdate(address,string,string)"(
      from?: string | null,
      name?: null,
      apiBaseUrl?: null
    ): ProviderUpdateEventFilter;
    ProviderUpdate(
      from?: string | null,
      name?: null,
      apiBaseUrl?: null
    ): ProviderUpdateEventFilter;

    "Register(uint256,address,uint256)"(
      id?: BigNumberish | null,
      from?: string | null,
      amount?: BigNumberish | null
    ): RegisterEventFilter;
    Register(
      id?: BigNumberish | null,
      from?: string | null,
      amount?: BigNumberish | null
    ): RegisterEventFilter;
  };

  estimateGas: {
    getProvider(
      providerAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getProviders(overrides?: CallOverrides): Promise<BigNumber>;

    getProvidersId(overrides?: CallOverrides): Promise<BigNumber>;

    isOperational(
      providerType: BigNumberish,
      addr: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pause(
      reason: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    pauseStatus(overrides?: CallOverrides): Promise<BigNumber>;

    register(
      name: string,
      apiBaseUrl: string,
      status: boolean,
      providerType: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    setProviderStatus(
      providerId: BigNumberish,
      status: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    unpause(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    updateProvider(
      name: string,
      apiBaseUrl: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getProvider(
      providerAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getProviders(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getProvidersId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isOperational(
      providerType: BigNumberish,
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pause(
      reason: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    pauseStatus(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    register(
      name: string,
      apiBaseUrl: string,
      status: boolean,
      providerType: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setProviderStatus(
      providerId: BigNumberish,
      status: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    updateProvider(
      name: string,
      apiBaseUrl: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
