/* Autogenerated file. Do not edit manually. */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export declare namespace IFlyoverConfigurations {
  export type ConfirmationTierStruct = {
    maxAmount: BigNumberish;
    confirmations: BigNumberish;
  };

  export type ConfirmationTierStructOutput = [BigNumber, BigNumber] & {
    maxAmount: BigNumber;
    confirmations: BigNumber;
  };

  export type PegConfigurationStruct = {
    fixedFee: BigNumberish;
    percentageFee: BigNumberish;
    penaltyFee: BigNumberish;
    confirmationTiers: IFlyoverConfigurations.ConfirmationTierStruct[];
    callTime: BigNumberish;
    expireTime: BigNumberish;
    expireBlocks: BigNumberish;
    deliveryGrace: BigNumberish;
    minAmount: BigNumberish;
    maxAmount: BigNumberish;
  };

  export type PegConfigurationStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    IFlyoverConfigurations.ConfirmationTierStructOutput[],
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    fixedFee: BigNumber;
    percentageFee: BigNumber;
    penaltyFee: BigNumber;
    confirmationTiers: IFlyoverConfigurations.ConfirmationTierStructOutput[];
    callTime: BigNumber;
    expireTime: BigNumber;
    expireBlocks: BigNumber;
    deliveryGrace: BigNumber;
    minAmount: BigNumber;
    maxAmount: BigNumber;
  };
}

export interface FlyoverConfigurationsInterface extends utils.Interface {
  functions: {
    "DEFAULT_ADMIN_ROLE()": FunctionFragment;
    "FEE_PERCENTAGE_DENOMINATOR()": FunctionFragment;
    "SAT_TO_WEI_CONVERSION()": FunctionFragment;
    "VERSION()": FunctionFragment;
    "acceptDefaultAdminTransfer()": FunctionFragment;
    "applyChange(uint8,uint8)": FunctionFragment;
    "applyTiersChange(uint8)": FunctionFragment;
    "beginDefaultAdminTransfer(address)": FunctionFragment;
    "calculatePegInFee(uint256)": FunctionFragment;
    "calculatePegOutFee(uint256)": FunctionFragment;
    "cancelDefaultAdminTransfer()": FunctionFragment;
    "changeDefaultAdminDelay(uint48)": FunctionFragment;
    "defaultAdmin()": FunctionFragment;
    "defaultAdminDelay()": FunctionFragment;
    "defaultAdminDelayIncreaseWait()": FunctionFragment;
    "getPegInConfiguration()": FunctionFragment;
    "getPegInConfigurationBounds()": FunctionFragment;
    "getPegOutConfiguration()": FunctionFragment;
    "getPegOutConfigurationBounds()": FunctionFragment;
    "getPendingChange(uint8,uint8)": FunctionFragment;
    "getRequiredPegInConfirmations(uint256)": FunctionFragment;
    "getRequiredPegOutConfirmations(uint256)": FunctionFragment;
    "getRoleAdmin(bytes32)": FunctionFragment;
    "getTimelockDelay()": FunctionFragment;
    "grantRole(bytes32,address)": FunctionFragment;
    "hasRole(bytes32,address)": FunctionFragment;
    "initialize(address,uint48,uint256,(uint256,uint256,uint256,(uint256,uint256)[],uint256,uint256,uint256,uint256,uint256,uint256),(uint256,uint256,uint256,(uint256,uint256)[],uint256,uint256,uint256,uint256,uint256,uint256),(uint256,uint256,uint256,(uint256,uint256)[],uint256,uint256,uint256,uint256,uint256,uint256),(uint256,uint256,uint256,(uint256,uint256)[],uint256,uint256,uint256,uint256,uint256,uint256),(uint256,uint256,uint256,(uint256,uint256)[],uint256,uint256,uint256,uint256,uint256,uint256),(uint256,uint256,uint256,(uint256,uint256)[],uint256,uint256,uint256,uint256,uint256,uint256))": FunctionFragment;
    "owner()": FunctionFragment;
    "pendingDefaultAdmin()": FunctionFragment;
    "pendingDefaultAdminDelay()": FunctionFragment;
    "queueChange(uint8,uint8,uint256)": FunctionFragment;
    "queueTiersChange(uint8,(uint256,uint256)[])": FunctionFragment;
    "renounceRole(bytes32,address)": FunctionFragment;
    "revokeRole(bytes32,address)": FunctionFragment;
    "rollbackDefaultAdminDelay()": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "DEFAULT_ADMIN_ROLE"
      | "FEE_PERCENTAGE_DENOMINATOR"
      | "SAT_TO_WEI_CONVERSION"
      | "VERSION"
      | "acceptDefaultAdminTransfer"
      | "applyChange"
      | "applyTiersChange"
      | "beginDefaultAdminTransfer"
      | "calculatePegInFee"
      | "calculatePegOutFee"
      | "cancelDefaultAdminTransfer"
      | "changeDefaultAdminDelay"
      | "defaultAdmin"
      | "defaultAdminDelay"
      | "defaultAdminDelayIncreaseWait"
      | "getPegInConfiguration"
      | "getPegInConfigurationBounds"
      | "getPegOutConfiguration"
      | "getPegOutConfigurationBounds"
      | "getPendingChange"
      | "getRequiredPegInConfirmations"
      | "getRequiredPegOutConfirmations"
      | "getRoleAdmin"
      | "getTimelockDelay"
      | "grantRole"
      | "hasRole"
      | "initialize"
      | "owner"
      | "pendingDefaultAdmin"
      | "pendingDefaultAdminDelay"
      | "queueChange"
      | "queueTiersChange"
      | "renounceRole"
      | "revokeRole"
      | "rollbackDefaultAdminDelay"
      | "supportsInterface"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FEE_PERCENTAGE_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SAT_TO_WEI_CONVERSION",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "VERSION", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "acceptDefaultAdminTransfer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "applyChange",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "applyTiersChange",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "beginDefaultAdminTransfer",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "calculatePegInFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculatePegOutFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelDefaultAdminTransfer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "changeDefaultAdminDelay",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "defaultAdminDelay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "defaultAdminDelayIncreaseWait",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPegInConfiguration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPegInConfigurationBounds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPegOutConfiguration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPegOutConfigurationBounds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingChange",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRequiredPegInConfirmations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRequiredPegOutConfirmations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTimelockDelay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      IFlyoverConfigurations.PegConfigurationStruct,
      IFlyoverConfigurations.PegConfigurationStruct,
      IFlyoverConfigurations.PegConfigurationStruct,
      IFlyoverConfigurations.PegConfigurationStruct,
      IFlyoverConfigurations.PegConfigurationStruct,
      IFlyoverConfigurations.PegConfigurationStruct
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingDefaultAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingDefaultAdminDelay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "queueChange",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "queueTiersChange",
    values: [BigNumberish, IFlyoverConfigurations.ConfirmationTierStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "rollbackDefaultAdminDelay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FEE_PERCENTAGE_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SAT_TO_WEI_CONVERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "VERSION", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "acceptDefaultAdminTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "applyChange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "applyTiersChange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beginDefaultAdminTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculatePegInFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculatePegOutFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelDefaultAdminTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeDefaultAdminDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultAdminDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultAdminDelayIncreaseWait",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPegInConfiguration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPegInConfigurationBounds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPegOutConfiguration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPegOutConfigurationBounds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingChange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRequiredPegInConfirmations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRequiredPegOutConfirmations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTimelockDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingDefaultAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingDefaultAdminDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "queueChange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "queueTiersChange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rollbackDefaultAdminDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;

  events: {
    "DefaultAdminDelayChangeCanceled()": EventFragment;
    "DefaultAdminDelayChangeScheduled(uint48,uint48)": EventFragment;
    "DefaultAdminTransferCanceled()": EventFragment;
    "DefaultAdminTransferScheduled(address,uint48)": EventFragment;
    "Initialized(uint64)": EventFragment;
    "PegInCallTimeChanged(uint256,uint256)": EventFragment;
    "PegInConfirmationTiersChanged((uint256,uint256)[],(uint256,uint256)[])": EventFragment;
    "PegInDeliveryGraceChanged(uint256,uint256)": EventFragment;
    "PegInExpireBlocksChanged(uint256,uint256)": EventFragment;
    "PegInExpireTimeChanged(uint256,uint256)": EventFragment;
    "PegInFixedFeeChanged(uint256,uint256)": EventFragment;
    "PegInMaxAmountChanged(uint256,uint256)": EventFragment;
    "PegInMinAmountChanged(uint256,uint256)": EventFragment;
    "PegInPenaltyFeeChanged(uint256,uint256)": EventFragment;
    "PegInPercentageFeeChanged(uint256,uint256)": EventFragment;
    "PegOutCallTimeChanged(uint256,uint256)": EventFragment;
    "PegOutConfirmationTiersChanged((uint256,uint256)[],(uint256,uint256)[])": EventFragment;
    "PegOutDeliveryGraceChanged(uint256,uint256)": EventFragment;
    "PegOutExpireBlocksChanged(uint256,uint256)": EventFragment;
    "PegOutExpireTimeChanged(uint256,uint256)": EventFragment;
    "PegOutFixedFeeChanged(uint256,uint256)": EventFragment;
    "PegOutMaxAmountChanged(uint256,uint256)": EventFragment;
    "PegOutMinAmountChanged(uint256,uint256)": EventFragment;
    "PegOutPenaltyFeeChanged(uint256,uint256)": EventFragment;
    "PegOutPercentageFeeChanged(uint256,uint256)": EventFragment;
    "RoleAdminChanged(bytes32,bytes32,bytes32)": EventFragment;
    "RoleGranted(bytes32,address,address)": EventFragment;
    "RoleRevoked(bytes32,address,address)": EventFragment;
  };

  getEvent(
    nameOrSignatureOrTopic: "DefaultAdminDelayChangeCanceled"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "DefaultAdminDelayChangeScheduled"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "DefaultAdminTransferCanceled"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "DefaultAdminTransferScheduled"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PegInCallTimeChanged"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "PegInConfirmationTiersChanged"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PegInDeliveryGraceChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PegInExpireBlocksChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PegInExpireTimeChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PegInFixedFeeChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PegInMaxAmountChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PegInMinAmountChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PegInPenaltyFeeChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PegInPercentageFeeChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PegOutCallTimeChanged"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "PegOutConfirmationTiersChanged"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PegOutDeliveryGraceChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PegOutExpireBlocksChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PegOutExpireTimeChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PegOutFixedFeeChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PegOutMaxAmountChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PegOutMinAmountChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PegOutPenaltyFeeChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PegOutPercentageFeeChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleAdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleRevoked"): EventFragment;
}

export interface DefaultAdminDelayChangeCanceledEventObject {}
export type DefaultAdminDelayChangeCanceledEvent = TypedEvent<
  [],
  DefaultAdminDelayChangeCanceledEventObject
>;

export type DefaultAdminDelayChangeCanceledEventFilter =
  TypedEventFilter<DefaultAdminDelayChangeCanceledEvent>;

export interface DefaultAdminDelayChangeScheduledEventObject {
  newDelay: number;
  effectSchedule: number;
}
export type DefaultAdminDelayChangeScheduledEvent = TypedEvent<
  [number, number],
  DefaultAdminDelayChangeScheduledEventObject
>;

export type DefaultAdminDelayChangeScheduledEventFilter =
  TypedEventFilter<DefaultAdminDelayChangeScheduledEvent>;

export interface DefaultAdminTransferCanceledEventObject {}
export type DefaultAdminTransferCanceledEvent = TypedEvent<
  [],
  DefaultAdminTransferCanceledEventObject
>;

export type DefaultAdminTransferCanceledEventFilter =
  TypedEventFilter<DefaultAdminTransferCanceledEvent>;

export interface DefaultAdminTransferScheduledEventObject {
  newAdmin: string;
  acceptSchedule: number;
}
export type DefaultAdminTransferScheduledEvent = TypedEvent<
  [string, number],
  DefaultAdminTransferScheduledEventObject
>;

export type DefaultAdminTransferScheduledEventFilter =
  TypedEventFilter<DefaultAdminTransferScheduledEvent>;

export interface InitializedEventObject {
  version: BigNumber;
}
export type InitializedEvent = TypedEvent<[BigNumber], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface PegInCallTimeChangedEventObject {
  oldValue: BigNumber;
  newValue: BigNumber;
}
export type PegInCallTimeChangedEvent = TypedEvent<
  [BigNumber, BigNumber],
  PegInCallTimeChangedEventObject
>;

export type PegInCallTimeChangedEventFilter =
  TypedEventFilter<PegInCallTimeChangedEvent>;

export interface PegInConfirmationTiersChangedEventObject {
  oldValue: IFlyoverConfigurations.ConfirmationTierStructOutput[];
  newValue: IFlyoverConfigurations.ConfirmationTierStructOutput[];
}
export type PegInConfirmationTiersChangedEvent = TypedEvent<
  [
    IFlyoverConfigurations.ConfirmationTierStructOutput[],
    IFlyoverConfigurations.ConfirmationTierStructOutput[]
  ],
  PegInConfirmationTiersChangedEventObject
>;

export type PegInConfirmationTiersChangedEventFilter =
  TypedEventFilter<PegInConfirmationTiersChangedEvent>;

export interface PegInDeliveryGraceChangedEventObject {
  oldValue: BigNumber;
  newValue: BigNumber;
}
export type PegInDeliveryGraceChangedEvent = TypedEvent<
  [BigNumber, BigNumber],
  PegInDeliveryGraceChangedEventObject
>;

export type PegInDeliveryGraceChangedEventFilter =
  TypedEventFilter<PegInDeliveryGraceChangedEvent>;

export interface PegInExpireBlocksChangedEventObject {
  oldValue: BigNumber;
  newValue: BigNumber;
}
export type PegInExpireBlocksChangedEvent = TypedEvent<
  [BigNumber, BigNumber],
  PegInExpireBlocksChangedEventObject
>;

export type PegInExpireBlocksChangedEventFilter =
  TypedEventFilter<PegInExpireBlocksChangedEvent>;

export interface PegInExpireTimeChangedEventObject {
  oldValue: BigNumber;
  newValue: BigNumber;
}
export type PegInExpireTimeChangedEvent = TypedEvent<
  [BigNumber, BigNumber],
  PegInExpireTimeChangedEventObject
>;

export type PegInExpireTimeChangedEventFilter =
  TypedEventFilter<PegInExpireTimeChangedEvent>;

export interface PegInFixedFeeChangedEventObject {
  oldValue: BigNumber;
  newValue: BigNumber;
}
export type PegInFixedFeeChangedEvent = TypedEvent<
  [BigNumber, BigNumber],
  PegInFixedFeeChangedEventObject
>;

export type PegInFixedFeeChangedEventFilter =
  TypedEventFilter<PegInFixedFeeChangedEvent>;

export interface PegInMaxAmountChangedEventObject {
  oldValue: BigNumber;
  newValue: BigNumber;
}
export type PegInMaxAmountChangedEvent = TypedEvent<
  [BigNumber, BigNumber],
  PegInMaxAmountChangedEventObject
>;

export type PegInMaxAmountChangedEventFilter =
  TypedEventFilter<PegInMaxAmountChangedEvent>;

export interface PegInMinAmountChangedEventObject {
  oldValue: BigNumber;
  newValue: BigNumber;
}
export type PegInMinAmountChangedEvent = TypedEvent<
  [BigNumber, BigNumber],
  PegInMinAmountChangedEventObject
>;

export type PegInMinAmountChangedEventFilter =
  TypedEventFilter<PegInMinAmountChangedEvent>;

export interface PegInPenaltyFeeChangedEventObject {
  oldValue: BigNumber;
  newValue: BigNumber;
}
export type PegInPenaltyFeeChangedEvent = TypedEvent<
  [BigNumber, BigNumber],
  PegInPenaltyFeeChangedEventObject
>;

export type PegInPenaltyFeeChangedEventFilter =
  TypedEventFilter<PegInPenaltyFeeChangedEvent>;

export interface PegInPercentageFeeChangedEventObject {
  oldValue: BigNumber;
  newValue: BigNumber;
}
export type PegInPercentageFeeChangedEvent = TypedEvent<
  [BigNumber, BigNumber],
  PegInPercentageFeeChangedEventObject
>;

export type PegInPercentageFeeChangedEventFilter =
  TypedEventFilter<PegInPercentageFeeChangedEvent>;

export interface PegOutCallTimeChangedEventObject {
  oldValue: BigNumber;
  newValue: BigNumber;
}
export type PegOutCallTimeChangedEvent = TypedEvent<
  [BigNumber, BigNumber],
  PegOutCallTimeChangedEventObject
>;

export type PegOutCallTimeChangedEventFilter =
  TypedEventFilter<PegOutCallTimeChangedEvent>;

export interface PegOutConfirmationTiersChangedEventObject {
  oldValue: IFlyoverConfigurations.ConfirmationTierStructOutput[];
  newValue: IFlyoverConfigurations.ConfirmationTierStructOutput[];
}
export type PegOutConfirmationTiersChangedEvent = TypedEvent<
  [
    IFlyoverConfigurations.ConfirmationTierStructOutput[],
    IFlyoverConfigurations.ConfirmationTierStructOutput[]
  ],
  PegOutConfirmationTiersChangedEventObject
>;

export type PegOutConfirmationTiersChangedEventFilter =
  TypedEventFilter<PegOutConfirmationTiersChangedEvent>;

export interface PegOutDeliveryGraceChangedEventObject {
  oldValue: BigNumber;
  newValue: BigNumber;
}
export type PegOutDeliveryGraceChangedEvent = TypedEvent<
  [BigNumber, BigNumber],
  PegOutDeliveryGraceChangedEventObject
>;

export type PegOutDeliveryGraceChangedEventFilter =
  TypedEventFilter<PegOutDeliveryGraceChangedEvent>;

export interface PegOutExpireBlocksChangedEventObject {
  oldValue: BigNumber;
  newValue: BigNumber;
}
export type PegOutExpireBlocksChangedEvent = TypedEvent<
  [BigNumber, BigNumber],
  PegOutExpireBlocksChangedEventObject
>;

export type PegOutExpireBlocksChangedEventFilter =
  TypedEventFilter<PegOutExpireBlocksChangedEvent>;

export interface PegOutExpireTimeChangedEventObject {
  oldValue: BigNumber;
  newValue: BigNumber;
}
export type PegOutExpireTimeChangedEvent = TypedEvent<
  [BigNumber, BigNumber],
  PegOutExpireTimeChangedEventObject
>;

export type PegOutExpireTimeChangedEventFilter =
  TypedEventFilter<PegOutExpireTimeChangedEvent>;

export interface PegOutFixedFeeChangedEventObject {
  oldValue: BigNumber;
  newValue: BigNumber;
}
export type PegOutFixedFeeChangedEvent = TypedEvent<
  [BigNumber, BigNumber],
  PegOutFixedFeeChangedEventObject
>;

export type PegOutFixedFeeChangedEventFilter =
  TypedEventFilter<PegOutFixedFeeChangedEvent>;

export interface PegOutMaxAmountChangedEventObject {
  oldValue: BigNumber;
  newValue: BigNumber;
}
export type PegOutMaxAmountChangedEvent = TypedEvent<
  [BigNumber, BigNumber],
  PegOutMaxAmountChangedEventObject
>;

export type PegOutMaxAmountChangedEventFilter =
  TypedEventFilter<PegOutMaxAmountChangedEvent>;

export interface PegOutMinAmountChangedEventObject {
  oldValue: BigNumber;
  newValue: BigNumber;
}
export type PegOutMinAmountChangedEvent = TypedEvent<
  [BigNumber, BigNumber],
  PegOutMinAmountChangedEventObject
>;

export type PegOutMinAmountChangedEventFilter =
  TypedEventFilter<PegOutMinAmountChangedEvent>;

export interface PegOutPenaltyFeeChangedEventObject {
  oldValue: BigNumber;
  newValue: BigNumber;
}
export type PegOutPenaltyFeeChangedEvent = TypedEvent<
  [BigNumber, BigNumber],
  PegOutPenaltyFeeChangedEventObject
>;

export type PegOutPenaltyFeeChangedEventFilter =
  TypedEventFilter<PegOutPenaltyFeeChangedEvent>;

export interface PegOutPercentageFeeChangedEventObject {
  oldValue: BigNumber;
  newValue: BigNumber;
}
export type PegOutPercentageFeeChangedEvent = TypedEvent<
  [BigNumber, BigNumber],
  PegOutPercentageFeeChangedEventObject
>;

export type PegOutPercentageFeeChangedEventFilter =
  TypedEventFilter<PegOutPercentageFeeChangedEvent>;

export interface RoleAdminChangedEventObject {
  role: string;
  previousAdminRole: string;
  newAdminRole: string;
}
export type RoleAdminChangedEvent = TypedEvent<
  [string, string, string],
  RoleAdminChangedEventObject
>;

export type RoleAdminChangedEventFilter =
  TypedEventFilter<RoleAdminChangedEvent>;

export interface RoleGrantedEventObject {
  role: string;
  account: string;
  sender: string;
}
export type RoleGrantedEvent = TypedEvent<
  [string, string, string],
  RoleGrantedEventObject
>;

export type RoleGrantedEventFilter = TypedEventFilter<RoleGrantedEvent>;

export interface RoleRevokedEventObject {
  role: string;
  account: string;
  sender: string;
}
export type RoleRevokedEvent = TypedEvent<
  [string, string, string],
  RoleRevokedEventObject
>;

export type RoleRevokedEventFilter = TypedEventFilter<RoleRevokedEvent>;

export interface FlyoverConfigurations extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: FlyoverConfigurationsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    FEE_PERCENTAGE_DENOMINATOR(overrides?: CallOverrides): Promise<[BigNumber]>;

    SAT_TO_WEI_CONVERSION(overrides?: CallOverrides): Promise<[BigNumber]>;

    VERSION(overrides?: CallOverrides): Promise<[string]>;

    acceptDefaultAdminTransfer(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    applyChange(
      flow: BigNumberish,
      field: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    applyTiersChange(
      flow: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    beginDefaultAdminTransfer(
      newAdmin: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    calculatePegInFee(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    calculatePegOutFee(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    cancelDefaultAdminTransfer(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    changeDefaultAdminDelay(
      newDelay: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    defaultAdmin(overrides?: CallOverrides): Promise<[string]>;

    defaultAdminDelay(overrides?: CallOverrides): Promise<[number]>;

    defaultAdminDelayIncreaseWait(overrides?: CallOverrides): Promise<[number]>;

    getPegInConfiguration(
      overrides?: CallOverrides
    ): Promise<[IFlyoverConfigurations.PegConfigurationStructOutput]>;

    getPegInConfigurationBounds(
      overrides?: CallOverrides
    ): Promise<
      [
        IFlyoverConfigurations.PegConfigurationStructOutput,
        IFlyoverConfigurations.PegConfigurationStructOutput
      ] & {
        min: IFlyoverConfigurations.PegConfigurationStructOutput;
        max: IFlyoverConfigurations.PegConfigurationStructOutput;
      }
    >;

    getPegOutConfiguration(
      overrides?: CallOverrides
    ): Promise<[IFlyoverConfigurations.PegConfigurationStructOutput]>;

    getPegOutConfigurationBounds(
      overrides?: CallOverrides
    ): Promise<
      [
        IFlyoverConfigurations.PegConfigurationStructOutput,
        IFlyoverConfigurations.PegConfigurationStructOutput
      ] & {
        min: IFlyoverConfigurations.PegConfigurationStructOutput;
        max: IFlyoverConfigurations.PegConfigurationStructOutput;
      }
    >;

    getPendingChange(
      flow: BigNumberish,
      field: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { value: BigNumber; eta: BigNumber }>;

    getRequiredPegInConfirmations(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getRequiredPegOutConfirmations(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    getTimelockDelay(overrides?: CallOverrides): Promise<[BigNumber]>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    initialize(
      defaultAdmin: string,
      initialDelay: BigNumberish,
      timelockDelay: BigNumberish,
      pegInConfig: IFlyoverConfigurations.PegConfigurationStruct,
      pegOutConfig: IFlyoverConfigurations.PegConfigurationStruct,
      pegInMin: IFlyoverConfigurations.PegConfigurationStruct,
      pegInMax: IFlyoverConfigurations.PegConfigurationStruct,
      pegOutMin: IFlyoverConfigurations.PegConfigurationStruct,
      pegOutMax: IFlyoverConfigurations.PegConfigurationStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pendingDefaultAdmin(
      overrides?: CallOverrides
    ): Promise<[string, number] & { newAdmin: string; schedule: number }>;

    pendingDefaultAdminDelay(
      overrides?: CallOverrides
    ): Promise<[number, number] & { newDelay: number; schedule: number }>;

    queueChange(
      flow: BigNumberish,
      field: BigNumberish,
      value: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    queueTiersChange(
      flow: BigNumberish,
      tiers: IFlyoverConfigurations.ConfirmationTierStruct[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    rollbackDefaultAdminDelay(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  FEE_PERCENTAGE_DENOMINATOR(overrides?: CallOverrides): Promise<BigNumber>;

  SAT_TO_WEI_CONVERSION(overrides?: CallOverrides): Promise<BigNumber>;

  VERSION(overrides?: CallOverrides): Promise<string>;

  acceptDefaultAdminTransfer(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  applyChange(
    flow: BigNumberish,
    field: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  applyTiersChange(
    flow: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  beginDefaultAdminTransfer(
    newAdmin: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  calculatePegInFee(
    amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  calculatePegOutFee(
    amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  cancelDefaultAdminTransfer(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  changeDefaultAdminDelay(
    newDelay: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  defaultAdmin(overrides?: CallOverrides): Promise<string>;

  defaultAdminDelay(overrides?: CallOverrides): Promise<number>;

  defaultAdminDelayIncreaseWait(overrides?: CallOverrides): Promise<number>;

  getPegInConfiguration(
    overrides?: CallOverrides
  ): Promise<IFlyoverConfigurations.PegConfigurationStructOutput>;

  getPegInConfigurationBounds(
    overrides?: CallOverrides
  ): Promise<
    [
      IFlyoverConfigurations.PegConfigurationStructOutput,
      IFlyoverConfigurations.PegConfigurationStructOutput
    ] & {
      min: IFlyoverConfigurations.PegConfigurationStructOutput;
      max: IFlyoverConfigurations.PegConfigurationStructOutput;
    }
  >;

  getPegOutConfiguration(
    overrides?: CallOverrides
  ): Promise<IFlyoverConfigurations.PegConfigurationStructOutput>;

  getPegOutConfigurationBounds(
    overrides?: CallOverrides
  ): Promise<
    [
      IFlyoverConfigurations.PegConfigurationStructOutput,
      IFlyoverConfigurations.PegConfigurationStructOutput
    ] & {
      min: IFlyoverConfigurations.PegConfigurationStructOutput;
      max: IFlyoverConfigurations.PegConfigurationStructOutput;
    }
  >;

  getPendingChange(
    flow: BigNumberish,
    field: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { value: BigNumber; eta: BigNumber }>;

  getRequiredPegInConfirmations(
    amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getRequiredPegOutConfirmations(
    amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

  getTimelockDelay(overrides?: CallOverrides): Promise<BigNumber>;

  grantRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  hasRole(
    role: BytesLike,
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  initialize(
    defaultAdmin: string,
    initialDelay: BigNumberish,
    timelockDelay: BigNumberish,
    pegInConfig: IFlyoverConfigurations.PegConfigurationStruct,
    pegOutConfig: IFlyoverConfigurations.PegConfigurationStruct,
    pegInMin: IFlyoverConfigurations.PegConfigurationStruct,
    pegInMax: IFlyoverConfigurations.PegConfigurationStruct,
    pegOutMin: IFlyoverConfigurations.PegConfigurationStruct,
    pegOutMax: IFlyoverConfigurations.PegConfigurationStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  pendingDefaultAdmin(
    overrides?: CallOverrides
  ): Promise<[string, number] & { newAdmin: string; schedule: number }>;

  pendingDefaultAdminDelay(
    overrides?: CallOverrides
  ): Promise<[number, number] & { newDelay: number; schedule: number }>;

  queueChange(
    flow: BigNumberish,
    field: BigNumberish,
    value: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  queueTiersChange(
    flow: BigNumberish,
    tiers: IFlyoverConfigurations.ConfirmationTierStruct[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  renounceRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  revokeRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  rollbackDefaultAdminDelay(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    FEE_PERCENTAGE_DENOMINATOR(overrides?: CallOverrides): Promise<BigNumber>;

    SAT_TO_WEI_CONVERSION(overrides?: CallOverrides): Promise<BigNumber>;

    VERSION(overrides?: CallOverrides): Promise<string>;

    acceptDefaultAdminTransfer(overrides?: CallOverrides): Promise<void>;

    applyChange(
      flow: BigNumberish,
      field: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    applyTiersChange(
      flow: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    beginDefaultAdminTransfer(
      newAdmin: string,
      overrides?: CallOverrides
    ): Promise<void>;

    calculatePegInFee(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculatePegOutFee(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    cancelDefaultAdminTransfer(overrides?: CallOverrides): Promise<void>;

    changeDefaultAdminDelay(
      newDelay: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    defaultAdmin(overrides?: CallOverrides): Promise<string>;

    defaultAdminDelay(overrides?: CallOverrides): Promise<number>;

    defaultAdminDelayIncreaseWait(overrides?: CallOverrides): Promise<number>;

    getPegInConfiguration(
      overrides?: CallOverrides
    ): Promise<IFlyoverConfigurations.PegConfigurationStructOutput>;

    getPegInConfigurationBounds(
      overrides?: CallOverrides
    ): Promise<
      [
        IFlyoverConfigurations.PegConfigurationStructOutput,
        IFlyoverConfigurations.PegConfigurationStructOutput
      ] & {
        min: IFlyoverConfigurations.PegConfigurationStructOutput;
        max: IFlyoverConfigurations.PegConfigurationStructOutput;
      }
    >;

    getPegOutConfiguration(
      overrides?: CallOverrides
    ): Promise<IFlyoverConfigurations.PegConfigurationStructOutput>;

    getPegOutConfigurationBounds(
      overrides?: CallOverrides
    ): Promise<
      [
        IFlyoverConfigurations.PegConfigurationStructOutput,
        IFlyoverConfigurations.PegConfigurationStructOutput
      ] & {
        min: IFlyoverConfigurations.PegConfigurationStructOutput;
        max: IFlyoverConfigurations.PegConfigurationStructOutput;
      }
    >;

    getPendingChange(
      flow: BigNumberish,
      field: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { value: BigNumber; eta: BigNumber }>;

    getRequiredPegInConfirmations(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRequiredPegOutConfirmations(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

    getTimelockDelay(overrides?: CallOverrides): Promise<BigNumber>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    initialize(
      defaultAdmin: string,
      initialDelay: BigNumberish,
      timelockDelay: BigNumberish,
      pegInConfig: IFlyoverConfigurations.PegConfigurationStruct,
      pegOutConfig: IFlyoverConfigurations.PegConfigurationStruct,
      pegInMin: IFlyoverConfigurations.PegConfigurationStruct,
      pegInMax: IFlyoverConfigurations.PegConfigurationStruct,
      pegOutMin: IFlyoverConfigurations.PegConfigurationStruct,
      pegOutMax: IFlyoverConfigurations.PegConfigurationStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    pendingDefaultAdmin(
      overrides?: CallOverrides
    ): Promise<[string, number] & { newAdmin: string; schedule: number }>;

    pendingDefaultAdminDelay(
      overrides?: CallOverrides
    ): Promise<[number, number] & { newDelay: number; schedule: number }>;

    queueChange(
      flow: BigNumberish,
      field: BigNumberish,
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    queueTiersChange(
      flow: BigNumberish,
      tiers: IFlyoverConfigurations.ConfirmationTierStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    rollbackDefaultAdminDelay(overrides?: CallOverrides): Promise<void>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "DefaultAdminDelayChangeCanceled()"(): DefaultAdminDelayChangeCanceledEventFilter;
    DefaultAdminDelayChangeCanceled(): DefaultAdminDelayChangeCanceledEventFilter;

    "DefaultAdminDelayChangeScheduled(uint48,uint48)"(
      newDelay?: null,
      effectSchedule?: null
    ): DefaultAdminDelayChangeScheduledEventFilter;
    DefaultAdminDelayChangeScheduled(
      newDelay?: null,
      effectSchedule?: null
    ): DefaultAdminDelayChangeScheduledEventFilter;

    "DefaultAdminTransferCanceled()"(): DefaultAdminTransferCanceledEventFilter;
    DefaultAdminTransferCanceled(): DefaultAdminTransferCanceledEventFilter;

    "DefaultAdminTransferScheduled(address,uint48)"(
      newAdmin?: string | null,
      acceptSchedule?: null
    ): DefaultAdminTransferScheduledEventFilter;
    DefaultAdminTransferScheduled(
      newAdmin?: string | null,
      acceptSchedule?: null
    ): DefaultAdminTransferScheduledEventFilter;

    "Initialized(uint64)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "PegInCallTimeChanged(uint256,uint256)"(
      oldValue?: null,
      newValue?: null
    ): PegInCallTimeChangedEventFilter;
    PegInCallTimeChanged(
      oldValue?: null,
      newValue?: null
    ): PegInCallTimeChangedEventFilter;

    "PegInConfirmationTiersChanged((uint256,uint256)[],(uint256,uint256)[])"(
      oldValue?: null,
      newValue?: null
    ): PegInConfirmationTiersChangedEventFilter;
    PegInConfirmationTiersChanged(
      oldValue?: null,
      newValue?: null
    ): PegInConfirmationTiersChangedEventFilter;

    "PegInDeliveryGraceChanged(uint256,uint256)"(
      oldValue?: null,
      newValue?: null
    ): PegInDeliveryGraceChangedEventFilter;
    PegInDeliveryGraceChanged(
      oldValue?: null,
      newValue?: null
    ): PegInDeliveryGraceChangedEventFilter;

    "PegInExpireBlocksChanged(uint256,uint256)"(
      oldValue?: null,
      newValue?: null
    ): PegInExpireBlocksChangedEventFilter;
    PegInExpireBlocksChanged(
      oldValue?: null,
      newValue?: null
    ): PegInExpireBlocksChangedEventFilter;

    "PegInExpireTimeChanged(uint256,uint256)"(
      oldValue?: null,
      newValue?: null
    ): PegInExpireTimeChangedEventFilter;
    PegInExpireTimeChanged(
      oldValue?: null,
      newValue?: null
    ): PegInExpireTimeChangedEventFilter;

    "PegInFixedFeeChanged(uint256,uint256)"(
      oldValue?: null,
      newValue?: null
    ): PegInFixedFeeChangedEventFilter;
    PegInFixedFeeChanged(
      oldValue?: null,
      newValue?: null
    ): PegInFixedFeeChangedEventFilter;

    "PegInMaxAmountChanged(uint256,uint256)"(
      oldValue?: null,
      newValue?: null
    ): PegInMaxAmountChangedEventFilter;
    PegInMaxAmountChanged(
      oldValue?: null,
      newValue?: null
    ): PegInMaxAmountChangedEventFilter;

    "PegInMinAmountChanged(uint256,uint256)"(
      oldValue?: null,
      newValue?: null
    ): PegInMinAmountChangedEventFilter;
    PegInMinAmountChanged(
      oldValue?: null,
      newValue?: null
    ): PegInMinAmountChangedEventFilter;

    "PegInPenaltyFeeChanged(uint256,uint256)"(
      oldValue?: null,
      newValue?: null
    ): PegInPenaltyFeeChangedEventFilter;
    PegInPenaltyFeeChanged(
      oldValue?: null,
      newValue?: null
    ): PegInPenaltyFeeChangedEventFilter;

    "PegInPercentageFeeChanged(uint256,uint256)"(
      oldValue?: null,
      newValue?: null
    ): PegInPercentageFeeChangedEventFilter;
    PegInPercentageFeeChanged(
      oldValue?: null,
      newValue?: null
    ): PegInPercentageFeeChangedEventFilter;

    "PegOutCallTimeChanged(uint256,uint256)"(
      oldValue?: null,
      newValue?: null
    ): PegOutCallTimeChangedEventFilter;
    PegOutCallTimeChanged(
      oldValue?: null,
      newValue?: null
    ): PegOutCallTimeChangedEventFilter;

    "PegOutConfirmationTiersChanged((uint256,uint256)[],(uint256,uint256)[])"(
      oldValue?: null,
      newValue?: null
    ): PegOutConfirmationTiersChangedEventFilter;
    PegOutConfirmationTiersChanged(
      oldValue?: null,
      newValue?: null
    ): PegOutConfirmationTiersChangedEventFilter;

    "PegOutDeliveryGraceChanged(uint256,uint256)"(
      oldValue?: null,
      newValue?: null
    ): PegOutDeliveryGraceChangedEventFilter;
    PegOutDeliveryGraceChanged(
      oldValue?: null,
      newValue?: null
    ): PegOutDeliveryGraceChangedEventFilter;

    "PegOutExpireBlocksChanged(uint256,uint256)"(
      oldValue?: null,
      newValue?: null
    ): PegOutExpireBlocksChangedEventFilter;
    PegOutExpireBlocksChanged(
      oldValue?: null,
      newValue?: null
    ): PegOutExpireBlocksChangedEventFilter;

    "PegOutExpireTimeChanged(uint256,uint256)"(
      oldValue?: null,
      newValue?: null
    ): PegOutExpireTimeChangedEventFilter;
    PegOutExpireTimeChanged(
      oldValue?: null,
      newValue?: null
    ): PegOutExpireTimeChangedEventFilter;

    "PegOutFixedFeeChanged(uint256,uint256)"(
      oldValue?: null,
      newValue?: null
    ): PegOutFixedFeeChangedEventFilter;
    PegOutFixedFeeChanged(
      oldValue?: null,
      newValue?: null
    ): PegOutFixedFeeChangedEventFilter;

    "PegOutMaxAmountChanged(uint256,uint256)"(
      oldValue?: null,
      newValue?: null
    ): PegOutMaxAmountChangedEventFilter;
    PegOutMaxAmountChanged(
      oldValue?: null,
      newValue?: null
    ): PegOutMaxAmountChangedEventFilter;

    "PegOutMinAmountChanged(uint256,uint256)"(
      oldValue?: null,
      newValue?: null
    ): PegOutMinAmountChangedEventFilter;
    PegOutMinAmountChanged(
      oldValue?: null,
      newValue?: null
    ): PegOutMinAmountChangedEventFilter;

    "PegOutPenaltyFeeChanged(uint256,uint256)"(
      oldValue?: null,
      newValue?: null
    ): PegOutPenaltyFeeChangedEventFilter;
    PegOutPenaltyFeeChanged(
      oldValue?: null,
      newValue?: null
    ): PegOutPenaltyFeeChangedEventFilter;

    "PegOutPercentageFeeChanged(uint256,uint256)"(
      oldValue?: null,
      newValue?: null
    ): PegOutPercentageFeeChangedEventFilter;
    PegOutPercentageFeeChanged(
      oldValue?: null,
      newValue?: null
    ): PegOutPercentageFeeChangedEventFilter;

    "RoleAdminChanged(bytes32,bytes32,bytes32)"(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null
    ): RoleAdminChangedEventFilter;
    RoleAdminChanged(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null
    ): RoleAdminChangedEventFilter;

    "RoleGranted(bytes32,address,address)"(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleGrantedEventFilter;
    RoleGranted(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleGrantedEventFilter;

    "RoleRevoked(bytes32,address,address)"(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleRevokedEventFilter;
    RoleRevoked(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleRevokedEventFilter;
  };

  estimateGas: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    FEE_PERCENTAGE_DENOMINATOR(overrides?: CallOverrides): Promise<BigNumber>;

    SAT_TO_WEI_CONVERSION(overrides?: CallOverrides): Promise<BigNumber>;

    VERSION(overrides?: CallOverrides): Promise<BigNumber>;

    acceptDefaultAdminTransfer(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    applyChange(
      flow: BigNumberish,
      field: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    applyTiersChange(
      flow: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    beginDefaultAdminTransfer(
      newAdmin: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    calculatePegInFee(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculatePegOutFee(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    cancelDefaultAdminTransfer(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    changeDefaultAdminDelay(
      newDelay: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    defaultAdmin(overrides?: CallOverrides): Promise<BigNumber>;

    defaultAdminDelay(overrides?: CallOverrides): Promise<BigNumber>;

    defaultAdminDelayIncreaseWait(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPegInConfiguration(overrides?: CallOverrides): Promise<BigNumber>;

    getPegInConfigurationBounds(overrides?: CallOverrides): Promise<BigNumber>;

    getPegOutConfiguration(overrides?: CallOverrides): Promise<BigNumber>;

    getPegOutConfigurationBounds(overrides?: CallOverrides): Promise<BigNumber>;

    getPendingChange(
      flow: BigNumberish,
      field: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRequiredPegInConfirmations(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRequiredPegOutConfirmations(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTimelockDelay(overrides?: CallOverrides): Promise<BigNumber>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      defaultAdmin: string,
      initialDelay: BigNumberish,
      timelockDelay: BigNumberish,
      pegInConfig: IFlyoverConfigurations.PegConfigurationStruct,
      pegOutConfig: IFlyoverConfigurations.PegConfigurationStruct,
      pegInMin: IFlyoverConfigurations.PegConfigurationStruct,
      pegInMax: IFlyoverConfigurations.PegConfigurationStruct,
      pegOutMin: IFlyoverConfigurations.PegConfigurationStruct,
      pegOutMax: IFlyoverConfigurations.PegConfigurationStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pendingDefaultAdmin(overrides?: CallOverrides): Promise<BigNumber>;

    pendingDefaultAdminDelay(overrides?: CallOverrides): Promise<BigNumber>;

    queueChange(
      flow: BigNumberish,
      field: BigNumberish,
      value: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    queueTiersChange(
      flow: BigNumberish,
      tiers: IFlyoverConfigurations.ConfirmationTierStruct[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    rollbackDefaultAdminDelay(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DEFAULT_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    FEE_PERCENTAGE_DENOMINATOR(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    SAT_TO_WEI_CONVERSION(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    VERSION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    acceptDefaultAdminTransfer(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    applyChange(
      flow: BigNumberish,
      field: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    applyTiersChange(
      flow: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    beginDefaultAdminTransfer(
      newAdmin: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    calculatePegInFee(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calculatePegOutFee(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    cancelDefaultAdminTransfer(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    changeDefaultAdminDelay(
      newDelay: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    defaultAdmin(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    defaultAdminDelay(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    defaultAdminDelayIncreaseWait(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPegInConfiguration(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPegInConfigurationBounds(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPegOutConfiguration(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPegOutConfigurationBounds(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPendingChange(
      flow: BigNumberish,
      field: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRequiredPegInConfirmations(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRequiredPegOutConfirmations(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTimelockDelay(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      defaultAdmin: string,
      initialDelay: BigNumberish,
      timelockDelay: BigNumberish,
      pegInConfig: IFlyoverConfigurations.PegConfigurationStruct,
      pegOutConfig: IFlyoverConfigurations.PegConfigurationStruct,
      pegInMin: IFlyoverConfigurations.PegConfigurationStruct,
      pegInMax: IFlyoverConfigurations.PegConfigurationStruct,
      pegOutMin: IFlyoverConfigurations.PegConfigurationStruct,
      pegOutMax: IFlyoverConfigurations.PegConfigurationStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pendingDefaultAdmin(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pendingDefaultAdminDelay(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    queueChange(
      flow: BigNumberish,
      field: BigNumberish,
      value: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    queueTiersChange(
      flow: BigNumberish,
      tiers: IFlyoverConfigurations.ConfirmationTierStruct[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    rollbackDefaultAdminDelay(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
