/* Autogenerated file. Do not edit manually. */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export declare namespace Quotes {
  export type PegInQuoteStruct = {
    callFee: BigNumberish;
    penaltyFee: BigNumberish;
    value: BigNumberish;
    productFeeAmount: BigNumberish;
    gasFee: BigNumberish;
    fedBtcAddress: BytesLike;
    lbcAddress: string;
    liquidityProviderRskAddress: string;
    contractAddress: string;
    rskRefundAddress: string;
    nonce: BigNumberish;
    gasLimit: BigNumberish;
    agreementTimestamp: BigNumberish;
    timeForDeposit: BigNumberish;
    callTime: BigNumberish;
    depositConfirmations: BigNumberish;
    callOnRegister: boolean;
    btcRefundAddress: BytesLike;
    liquidityProviderBtcAddress: BytesLike;
    data: BytesLike;
  };

  export type PegInQuoteStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    string,
    string,
    string,
    string,
    BigNumber,
    number,
    number,
    number,
    number,
    number,
    boolean,
    string,
    string,
    string
  ] & {
    callFee: BigNumber;
    penaltyFee: BigNumber;
    value: BigNumber;
    productFeeAmount: BigNumber;
    gasFee: BigNumber;
    fedBtcAddress: string;
    lbcAddress: string;
    liquidityProviderRskAddress: string;
    contractAddress: string;
    rskRefundAddress: string;
    nonce: BigNumber;
    gasLimit: number;
    agreementTimestamp: number;
    timeForDeposit: number;
    callTime: number;
    depositConfirmations: number;
    callOnRegister: boolean;
    btcRefundAddress: string;
    liquidityProviderBtcAddress: string;
    data: string;
  };
}

export interface PeginInterface extends utils.Interface {
  functions: {
    "callForUser((uint256,uint256,uint256,uint256,uint256,bytes20,address,address,address,address,int64,uint32,uint32,uint32,uint32,uint16,bool,bytes,bytes,bytes))": FunctionFragment;
    "deposit()": FunctionFragment;
    "getBalance(address)": FunctionFragment;
    "getCurrentContribution()": FunctionFragment;
    "getFeeCollector()": FunctionFragment;
    "getFeePercentage()": FunctionFragment;
    "getMinPegIn()": FunctionFragment;
    "getQuoteStatus(bytes32)": FunctionFragment;
    "hashPegInQuote((uint256,uint256,uint256,uint256,uint256,bytes20,address,address,address,address,int64,uint32,uint32,uint32,uint32,uint16,bool,bytes,bytes,bytes))": FunctionFragment;
    "pause(string)": FunctionFragment;
    "pauseStatus()": FunctionFragment;
    "registerPegIn((uint256,uint256,uint256,uint256,uint256,bytes20,address,address,address,address,int64,uint32,uint32,uint32,uint32,uint16,bool,bytes,bytes,bytes),bytes,bytes,bytes,uint256)": FunctionFragment;
    "unpause()": FunctionFragment;
    "validatePegInDepositAddress((uint256,uint256,uint256,uint256,uint256,bytes20,address,address,address,address,int64,uint32,uint32,uint32,uint32,uint16,bool,bytes,bytes,bytes),bytes)": FunctionFragment;
    "withdraw(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "callForUser"
      | "deposit"
      | "getBalance"
      | "getCurrentContribution"
      | "getFeeCollector"
      | "getFeePercentage"
      | "getMinPegIn"
      | "getQuoteStatus"
      | "hashPegInQuote"
      | "pause"
      | "pauseStatus"
      | "registerPegIn"
      | "unpause"
      | "validatePegInDepositAddress"
      | "withdraw"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "callForUser",
    values: [Quotes.PegInQuoteStruct]
  ): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(functionFragment: "getBalance", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getCurrentContribution",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFeeCollector",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFeePercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMinPegIn",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getQuoteStatus",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hashPegInQuote",
    values: [Quotes.PegInQuoteStruct]
  ): string;
  encodeFunctionData(functionFragment: "pause", values: [string]): string;
  encodeFunctionData(
    functionFragment: "pauseStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerPegIn",
    values: [
      Quotes.PegInQuoteStruct,
      BytesLike,
      BytesLike,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "validatePegInDepositAddress",
    values: [Quotes.PegInQuoteStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "callForUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMinPegIn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getQuoteStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hashPegInQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pauseStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerPegIn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "validatePegInDepositAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "BalanceDecrease(address,uint256)": EventFragment;
    "BalanceIncrease(address,uint256)": EventFragment;
    "BridgeCapExceeded(bytes32,int256)": EventFragment;
    "CallForUser(address,address,bytes32,uint256,uint256,bytes,bool)": EventFragment;
    "PegInRegistered(bytes32,uint256)": EventFragment;
    "Refund(address,bytes32,uint256,bool)": EventFragment;
    "Withdrawal(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BalanceDecrease"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BalanceIncrease"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BridgeCapExceeded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CallForUser"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PegInRegistered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Refund"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Withdrawal"): EventFragment;
}

export interface BalanceDecreaseEventObject {
  dest: string;
  amount: BigNumber;
}
export type BalanceDecreaseEvent = TypedEvent<
  [string, BigNumber],
  BalanceDecreaseEventObject
>;

export type BalanceDecreaseEventFilter = TypedEventFilter<BalanceDecreaseEvent>;

export interface BalanceIncreaseEventObject {
  dest: string;
  amount: BigNumber;
}
export type BalanceIncreaseEvent = TypedEvent<
  [string, BigNumber],
  BalanceIncreaseEventObject
>;

export type BalanceIncreaseEventFilter = TypedEventFilter<BalanceIncreaseEvent>;

export interface BridgeCapExceededEventObject {
  quoteHash: string;
  errorCode: BigNumber;
}
export type BridgeCapExceededEvent = TypedEvent<
  [string, BigNumber],
  BridgeCapExceededEventObject
>;

export type BridgeCapExceededEventFilter =
  TypedEventFilter<BridgeCapExceededEvent>;

export interface CallForUserEventObject {
  from: string;
  dest: string;
  quoteHash: string;
  gasLimit: BigNumber;
  value: BigNumber;
  data: string;
  success: boolean;
}
export type CallForUserEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber, string, boolean],
  CallForUserEventObject
>;

export type CallForUserEventFilter = TypedEventFilter<CallForUserEvent>;

export interface PegInRegisteredEventObject {
  quoteHash: string;
  transferredAmount: BigNumber;
}
export type PegInRegisteredEvent = TypedEvent<
  [string, BigNumber],
  PegInRegisteredEventObject
>;

export type PegInRegisteredEventFilter = TypedEventFilter<PegInRegisteredEvent>;

export interface RefundEventObject {
  dest: string;
  quoteHash: string;
  amount: BigNumber;
  success: boolean;
}
export type RefundEvent = TypedEvent<
  [string, string, BigNumber, boolean],
  RefundEventObject
>;

export type RefundEventFilter = TypedEventFilter<RefundEvent>;

export interface WithdrawalEventObject {
  from: string;
  amount: BigNumber;
}
export type WithdrawalEvent = TypedEvent<
  [string, BigNumber],
  WithdrawalEventObject
>;

export type WithdrawalEventFilter = TypedEventFilter<WithdrawalEvent>;

export interface Pegin extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PeginInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    callForUser(
      quote: Quotes.PegInQuoteStruct,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    deposit(
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    getBalance(addr: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    getCurrentContribution(overrides?: CallOverrides): Promise<[BigNumber]>;

    getFeeCollector(overrides?: CallOverrides): Promise<[string]>;

    getFeePercentage(overrides?: CallOverrides): Promise<[BigNumber]>;

    getMinPegIn(overrides?: CallOverrides): Promise<[BigNumber]>;

    getQuoteStatus(
      quoteHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<[number]>;

    hashPegInQuote(
      quote: Quotes.PegInQuoteStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;

    pause(
      reason: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    pauseStatus(
      overrides?: CallOverrides
    ): Promise<
      [boolean, string, BigNumber] & {
        isPaused: boolean;
        reason: string;
        since: BigNumber;
      }
    >;

    registerPegIn(
      quote: Quotes.PegInQuoteStruct,
      signature: BytesLike,
      btcRawTransaction: BytesLike,
      partialMerkleTree: BytesLike,
      height: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    unpause(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    validatePegInDepositAddress(
      quote: Quotes.PegInQuoteStruct,
      depositAddress: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    withdraw(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  callForUser(
    quote: Quotes.PegInQuoteStruct,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  deposit(
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  getBalance(addr: string, overrides?: CallOverrides): Promise<BigNumber>;

  getCurrentContribution(overrides?: CallOverrides): Promise<BigNumber>;

  getFeeCollector(overrides?: CallOverrides): Promise<string>;

  getFeePercentage(overrides?: CallOverrides): Promise<BigNumber>;

  getMinPegIn(overrides?: CallOverrides): Promise<BigNumber>;

  getQuoteStatus(
    quoteHash: BytesLike,
    overrides?: CallOverrides
  ): Promise<number>;

  hashPegInQuote(
    quote: Quotes.PegInQuoteStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  pause(
    reason: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  pauseStatus(
    overrides?: CallOverrides
  ): Promise<
    [boolean, string, BigNumber] & {
      isPaused: boolean;
      reason: string;
      since: BigNumber;
    }
  >;

  registerPegIn(
    quote: Quotes.PegInQuoteStruct,
    signature: BytesLike,
    btcRawTransaction: BytesLike,
    partialMerkleTree: BytesLike,
    height: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  unpause(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  validatePegInDepositAddress(
    quote: Quotes.PegInQuoteStruct,
    depositAddress: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  withdraw(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    callForUser(
      quote: Quotes.PegInQuoteStruct,
      overrides?: CallOverrides
    ): Promise<boolean>;

    deposit(overrides?: CallOverrides): Promise<void>;

    getBalance(addr: string, overrides?: CallOverrides): Promise<BigNumber>;

    getCurrentContribution(overrides?: CallOverrides): Promise<BigNumber>;

    getFeeCollector(overrides?: CallOverrides): Promise<string>;

    getFeePercentage(overrides?: CallOverrides): Promise<BigNumber>;

    getMinPegIn(overrides?: CallOverrides): Promise<BigNumber>;

    getQuoteStatus(
      quoteHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<number>;

    hashPegInQuote(
      quote: Quotes.PegInQuoteStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    pause(reason: string, overrides?: CallOverrides): Promise<void>;

    pauseStatus(
      overrides?: CallOverrides
    ): Promise<
      [boolean, string, BigNumber] & {
        isPaused: boolean;
        reason: string;
        since: BigNumber;
      }
    >;

    registerPegIn(
      quote: Quotes.PegInQuoteStruct,
      signature: BytesLike,
      btcRawTransaction: BytesLike,
      partialMerkleTree: BytesLike,
      height: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    unpause(overrides?: CallOverrides): Promise<void>;

    validatePegInDepositAddress(
      quote: Quotes.PegInQuoteStruct,
      depositAddress: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    withdraw(amount: BigNumberish, overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "BalanceDecrease(address,uint256)"(
      dest?: string | null,
      amount?: BigNumberish | null
    ): BalanceDecreaseEventFilter;
    BalanceDecrease(
      dest?: string | null,
      amount?: BigNumberish | null
    ): BalanceDecreaseEventFilter;

    "BalanceIncrease(address,uint256)"(
      dest?: string | null,
      amount?: BigNumberish | null
    ): BalanceIncreaseEventFilter;
    BalanceIncrease(
      dest?: string | null,
      amount?: BigNumberish | null
    ): BalanceIncreaseEventFilter;

    "BridgeCapExceeded(bytes32,int256)"(
      quoteHash?: BytesLike | null,
      errorCode?: BigNumberish | null
    ): BridgeCapExceededEventFilter;
    BridgeCapExceeded(
      quoteHash?: BytesLike | null,
      errorCode?: BigNumberish | null
    ): BridgeCapExceededEventFilter;

    "CallForUser(address,address,bytes32,uint256,uint256,bytes,bool)"(
      from?: string | null,
      dest?: string | null,
      quoteHash?: BytesLike | null,
      gasLimit?: null,
      value?: null,
      data?: null,
      success?: null
    ): CallForUserEventFilter;
    CallForUser(
      from?: string | null,
      dest?: string | null,
      quoteHash?: BytesLike | null,
      gasLimit?: null,
      value?: null,
      data?: null,
      success?: null
    ): CallForUserEventFilter;

    "PegInRegistered(bytes32,uint256)"(
      quoteHash?: BytesLike | null,
      transferredAmount?: BigNumberish | null
    ): PegInRegisteredEventFilter;
    PegInRegistered(
      quoteHash?: BytesLike | null,
      transferredAmount?: BigNumberish | null
    ): PegInRegisteredEventFilter;

    "Refund(address,bytes32,uint256,bool)"(
      dest?: string | null,
      quoteHash?: BytesLike | null,
      amount?: BigNumberish | null,
      success?: null
    ): RefundEventFilter;
    Refund(
      dest?: string | null,
      quoteHash?: BytesLike | null,
      amount?: BigNumberish | null,
      success?: null
    ): RefundEventFilter;

    "Withdrawal(address,uint256)"(
      from?: string | null,
      amount?: BigNumberish | null
    ): WithdrawalEventFilter;
    Withdrawal(
      from?: string | null,
      amount?: BigNumberish | null
    ): WithdrawalEventFilter;
  };

  estimateGas: {
    callForUser(
      quote: Quotes.PegInQuoteStruct,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    deposit(
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    getBalance(addr: string, overrides?: CallOverrides): Promise<BigNumber>;

    getCurrentContribution(overrides?: CallOverrides): Promise<BigNumber>;

    getFeeCollector(overrides?: CallOverrides): Promise<BigNumber>;

    getFeePercentage(overrides?: CallOverrides): Promise<BigNumber>;

    getMinPegIn(overrides?: CallOverrides): Promise<BigNumber>;

    getQuoteStatus(
      quoteHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hashPegInQuote(
      quote: Quotes.PegInQuoteStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pause(
      reason: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    pauseStatus(overrides?: CallOverrides): Promise<BigNumber>;

    registerPegIn(
      quote: Quotes.PegInQuoteStruct,
      signature: BytesLike,
      btcRawTransaction: BytesLike,
      partialMerkleTree: BytesLike,
      height: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    unpause(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    validatePegInDepositAddress(
      quote: Quotes.PegInQuoteStruct,
      depositAddress: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdraw(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    callForUser(
      quote: Quotes.PegInQuoteStruct,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    deposit(
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getBalance(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCurrentContribution(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFeeCollector(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getFeePercentage(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getMinPegIn(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getQuoteStatus(
      quoteHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hashPegInQuote(
      quote: Quotes.PegInQuoteStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pause(
      reason: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    pauseStatus(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    registerPegIn(
      quote: Quotes.PegInQuoteStruct,
      signature: BytesLike,
      btcRawTransaction: BytesLike,
      partialMerkleTree: BytesLike,
      height: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    validatePegInDepositAddress(
      quote: Quotes.PegInQuoteStruct,
      depositAddress: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdraw(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
