/* Autogenerated file. Do not edit manually. */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export declare namespace Quotes {
  export type PegOutQuoteStruct = {
    callFee: BigNumberish;
    penaltyFee: BigNumberish;
    value: BigNumberish;
    productFeeAmount: BigNumberish;
    gasFee: BigNumberish;
    lbcAddress: string;
    lpRskAddress: string;
    rskRefundAddress: string;
    nonce: BigNumberish;
    agreementTimestamp: BigNumberish;
    depositDateLimit: BigNumberish;
    transferTime: BigNumberish;
    expireDate: BigNumberish;
    expireBlock: BigNumberish;
    depositConfirmations: BigNumberish;
    transferConfirmations: BigNumberish;
    depositAddress: BytesLike;
    btcRefundAddress: BytesLike;
    lpBtcAddress: BytesLike;
  };

  export type PegOutQuoteStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    string,
    string,
    BigNumber,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    string,
    string,
    string
  ] & {
    callFee: BigNumber;
    penaltyFee: BigNumber;
    value: BigNumber;
    productFeeAmount: BigNumber;
    gasFee: BigNumber;
    lbcAddress: string;
    lpRskAddress: string;
    rskRefundAddress: string;
    nonce: BigNumber;
    agreementTimestamp: number;
    depositDateLimit: number;
    transferTime: number;
    expireDate: number;
    expireBlock: number;
    depositConfirmations: number;
    transferConfirmations: number;
    depositAddress: string;
    btcRefundAddress: string;
    lpBtcAddress: string;
  };
}

export interface PegoutInterface extends utils.Interface {
  functions: {
    "depositPegOut((uint256,uint256,uint256,uint256,uint256,address,address,address,int64,uint32,uint32,uint32,uint32,uint32,uint16,uint16,bytes,bytes,bytes),bytes)": FunctionFragment;
    "getCurrentContribution()": FunctionFragment;
    "getFeeCollector()": FunctionFragment;
    "getFeePercentage()": FunctionFragment;
    "hashPegOutQuote((uint256,uint256,uint256,uint256,uint256,address,address,address,int64,uint32,uint32,uint32,uint32,uint32,uint16,uint16,bytes,bytes,bytes))": FunctionFragment;
    "isQuoteCompleted(bytes32)": FunctionFragment;
    "pause(string)": FunctionFragment;
    "pauseStatus()": FunctionFragment;
    "refundPegOut(bytes32,bytes,bytes32,uint256,bytes32[])": FunctionFragment;
    "refundUserPegOut(bytes32)": FunctionFragment;
    "unpause()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "depositPegOut"
      | "getCurrentContribution"
      | "getFeeCollector"
      | "getFeePercentage"
      | "hashPegOutQuote"
      | "isQuoteCompleted"
      | "pause"
      | "pauseStatus"
      | "refundPegOut"
      | "refundUserPegOut"
      | "unpause"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "depositPegOut",
    values: [Quotes.PegOutQuoteStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentContribution",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFeeCollector",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFeePercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hashPegOutQuote",
    values: [Quotes.PegOutQuoteStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "isQuoteCompleted",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "pause", values: [string]): string;
  encodeFunctionData(
    functionFragment: "pauseStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "refundPegOut",
    values: [BytesLike, BytesLike, BytesLike, BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "refundUserPegOut",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "depositPegOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hashPegOutQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isQuoteCompleted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pauseStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refundPegOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refundUserPegOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;

  events: {
    "PegOutChangePaid(bytes32,address,uint256)": EventFragment;
    "PegOutDeposit(bytes32,address,uint256,uint256)": EventFragment;
    "PegOutRefunded(bytes32)": EventFragment;
    "PegOutUserRefunded(bytes32,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "PegOutChangePaid"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PegOutDeposit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PegOutRefunded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PegOutUserRefunded"): EventFragment;
}

export interface PegOutChangePaidEventObject {
  quoteHash: string;
  userAddress: string;
  change: BigNumber;
}
export type PegOutChangePaidEvent = TypedEvent<
  [string, string, BigNumber],
  PegOutChangePaidEventObject
>;

export type PegOutChangePaidEventFilter =
  TypedEventFilter<PegOutChangePaidEvent>;

export interface PegOutDepositEventObject {
  quoteHash: string;
  sender: string;
  timestamp: BigNumber;
  amount: BigNumber;
}
export type PegOutDepositEvent = TypedEvent<
  [string, string, BigNumber, BigNumber],
  PegOutDepositEventObject
>;

export type PegOutDepositEventFilter = TypedEventFilter<PegOutDepositEvent>;

export interface PegOutRefundedEventObject {
  quoteHash: string;
}
export type PegOutRefundedEvent = TypedEvent<
  [string],
  PegOutRefundedEventObject
>;

export type PegOutRefundedEventFilter = TypedEventFilter<PegOutRefundedEvent>;

export interface PegOutUserRefundedEventObject {
  quoteHash: string;
  userAddress: string;
  value: BigNumber;
}
export type PegOutUserRefundedEvent = TypedEvent<
  [string, string, BigNumber],
  PegOutUserRefundedEventObject
>;

export type PegOutUserRefundedEventFilter =
  TypedEventFilter<PegOutUserRefundedEvent>;

export interface Pegout extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PegoutInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    depositPegOut(
      quote: Quotes.PegOutQuoteStruct,
      signature: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    getCurrentContribution(overrides?: CallOverrides): Promise<[BigNumber]>;

    getFeeCollector(overrides?: CallOverrides): Promise<[string]>;

    getFeePercentage(overrides?: CallOverrides): Promise<[BigNumber]>;

    hashPegOutQuote(
      quote: Quotes.PegOutQuoteStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;

    isQuoteCompleted(
      quoteHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    pause(
      reason: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    pauseStatus(
      overrides?: CallOverrides
    ): Promise<
      [boolean, string, BigNumber] & {
        isPaused: boolean;
        reason: string;
        since: BigNumber;
      }
    >;

    refundPegOut(
      quoteHash: BytesLike,
      btcTx: BytesLike,
      btcBlockHeaderHash: BytesLike,
      merkleBranchPath: BigNumberish,
      merkleBranchHashes: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    refundUserPegOut(
      quoteHash: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    unpause(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  depositPegOut(
    quote: Quotes.PegOutQuoteStruct,
    signature: BytesLike,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  getCurrentContribution(overrides?: CallOverrides): Promise<BigNumber>;

  getFeeCollector(overrides?: CallOverrides): Promise<string>;

  getFeePercentage(overrides?: CallOverrides): Promise<BigNumber>;

  hashPegOutQuote(
    quote: Quotes.PegOutQuoteStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  isQuoteCompleted(
    quoteHash: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  pause(
    reason: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  pauseStatus(
    overrides?: CallOverrides
  ): Promise<
    [boolean, string, BigNumber] & {
      isPaused: boolean;
      reason: string;
      since: BigNumber;
    }
  >;

  refundPegOut(
    quoteHash: BytesLike,
    btcTx: BytesLike,
    btcBlockHeaderHash: BytesLike,
    merkleBranchPath: BigNumberish,
    merkleBranchHashes: BytesLike[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  refundUserPegOut(
    quoteHash: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  unpause(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    depositPegOut(
      quote: Quotes.PegOutQuoteStruct,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    getCurrentContribution(overrides?: CallOverrides): Promise<BigNumber>;

    getFeeCollector(overrides?: CallOverrides): Promise<string>;

    getFeePercentage(overrides?: CallOverrides): Promise<BigNumber>;

    hashPegOutQuote(
      quote: Quotes.PegOutQuoteStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    isQuoteCompleted(
      quoteHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    pause(reason: string, overrides?: CallOverrides): Promise<void>;

    pauseStatus(
      overrides?: CallOverrides
    ): Promise<
      [boolean, string, BigNumber] & {
        isPaused: boolean;
        reason: string;
        since: BigNumber;
      }
    >;

    refundPegOut(
      quoteHash: BytesLike,
      btcTx: BytesLike,
      btcBlockHeaderHash: BytesLike,
      merkleBranchPath: BigNumberish,
      merkleBranchHashes: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    refundUserPegOut(
      quoteHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    unpause(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "PegOutChangePaid(bytes32,address,uint256)"(
      quoteHash?: BytesLike | null,
      userAddress?: string | null,
      change?: BigNumberish | null
    ): PegOutChangePaidEventFilter;
    PegOutChangePaid(
      quoteHash?: BytesLike | null,
      userAddress?: string | null,
      change?: BigNumberish | null
    ): PegOutChangePaidEventFilter;

    "PegOutDeposit(bytes32,address,uint256,uint256)"(
      quoteHash?: BytesLike | null,
      sender?: string | null,
      timestamp?: BigNumberish | null,
      amount?: null
    ): PegOutDepositEventFilter;
    PegOutDeposit(
      quoteHash?: BytesLike | null,
      sender?: string | null,
      timestamp?: BigNumberish | null,
      amount?: null
    ): PegOutDepositEventFilter;

    "PegOutRefunded(bytes32)"(
      quoteHash?: BytesLike | null
    ): PegOutRefundedEventFilter;
    PegOutRefunded(quoteHash?: BytesLike | null): PegOutRefundedEventFilter;

    "PegOutUserRefunded(bytes32,address,uint256)"(
      quoteHash?: BytesLike | null,
      userAddress?: string | null,
      value?: BigNumberish | null
    ): PegOutUserRefundedEventFilter;
    PegOutUserRefunded(
      quoteHash?: BytesLike | null,
      userAddress?: string | null,
      value?: BigNumberish | null
    ): PegOutUserRefundedEventFilter;
  };

  estimateGas: {
    depositPegOut(
      quote: Quotes.PegOutQuoteStruct,
      signature: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    getCurrentContribution(overrides?: CallOverrides): Promise<BigNumber>;

    getFeeCollector(overrides?: CallOverrides): Promise<BigNumber>;

    getFeePercentage(overrides?: CallOverrides): Promise<BigNumber>;

    hashPegOutQuote(
      quote: Quotes.PegOutQuoteStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isQuoteCompleted(
      quoteHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pause(
      reason: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    pauseStatus(overrides?: CallOverrides): Promise<BigNumber>;

    refundPegOut(
      quoteHash: BytesLike,
      btcTx: BytesLike,
      btcBlockHeaderHash: BytesLike,
      merkleBranchPath: BigNumberish,
      merkleBranchHashes: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    refundUserPegOut(
      quoteHash: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    unpause(overrides?: Overrides & { from?: string }): Promise<BigNumber>;
  };

  populateTransaction: {
    depositPegOut(
      quote: Quotes.PegOutQuoteStruct,
      signature: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getCurrentContribution(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFeeCollector(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getFeePercentage(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    hashPegOutQuote(
      quote: Quotes.PegOutQuoteStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isQuoteCompleted(
      quoteHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pause(
      reason: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    pauseStatus(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    refundPegOut(
      quoteHash: BytesLike,
      btcTx: BytesLike,
      btcBlockHeaderHash: BytesLike,
      merkleBranchPath: BigNumberish,
      merkleBranchHashes: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    refundUserPegOut(
      quoteHash: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
